import type { EdgeType } from '@vh/core';

/**
 * Phosphor 图标映射（图标名，供 <Icon> 封装消费）。
 * 见 docs-internal/UI设计规范.md §5。图标名对应 @phosphor-icons/react 组件名。
 */

/** 分类 id -> Phosphor 图标名（section + 常用 leaf） */
export const CATEGORY_ICONS: Record<string, string> = {
  'coding-agent': 'Robot',
  'coding-ide-agent': 'Desktop',
  'coding-cloud-builder': 'CloudArrowUp',
  'coding-cli-agent': 'Terminal',
  'coding-async-agent': 'Timer',
  'coding-completion': 'Lightning',
  'coding-review': 'GitPullRequest',
  llm: 'Brain',
  'llm-family': 'TreeStructure',
  'llm-line': 'GitBranch',
  'llm-frontier': 'Brain',
  'model-gateway': 'Plugs',
  'gateway-router': 'Plugs',
  'gateway-local': 'HardDrives',
  'language-runtime': 'Code',
  'lang-language': 'Code',
  'lang-runtime': 'Cpu',
  framework: 'Stack',
  'fw-fullstack': 'Stack',
  'fw-ui-lib': 'Browsers',
  'ui-library': 'Layout',
  'ui-kits': 'SquaresFour',
  'ui-composable': 'PuzzlePiece',
  'ui-primitives': 'Cube',
  'ui-icons': 'Smiley',
  'cloud-deploy': 'Cloud',
  'cloud-paas': 'Cloud',
  'database-storage': 'Database',
  'db-relational': 'Database',
  'db-nosql': 'CirclesThreePlus',
  'db-cache': 'Lightning',
  'db-object': 'Archive',
  'db-sqlite-edge': 'HardDrive',
  'baas-auth': 'LockKey',
  'baas-platform': 'LockKey',
  'baas-auth-only': 'Fingerprint',
  'ai-infra': 'Atom',
  'ai-agent-fw': 'Graph',
  'ai-rag': 'Books',
  'ai-vector': 'Hexagon',
  'ai-llm-obs': 'Eye',
  'ai-speech': 'SpeakerHigh',
  'ai-realtime': 'Waveform',
  'ai-ocr': 'Scan',
  payment: 'CreditCard',
  'pay-processor': 'CreditCard',
  'pay-mor': 'Receipt',
  'app-distribution': 'Storefront',
  'dist-ios': 'AppleLogo',
  'dist-android': 'GooglePlayLogo',
  'dist-extension': 'PuzzlePiece',
  'dist-desktop': 'DesktopTower',
  'oss-ecosystem': 'Package',
  'oss-toolchain': 'Wrench',
  observability: 'Pulse',
  'obs-errors': 'Bug',
  'obs-product': 'ChartBar',
  'obs-platform': 'Pulse',
  'cicd-devops': 'Infinity',
  'cicd-pipeline': 'Infinity',
  messaging: 'PaperPlaneTilt',
  'msg-email': 'Envelope',
  'msg-sms': 'ChatText',
  'msg-push': 'Bell',
  'msg-im': 'ChatsCircle',
  'analytics-growth': 'ChartLineUp',
  'growth-web': 'ChartLineUp',
  'domain-dns-cdn': 'Globe',
  'net-cdn-dns': 'Globe',
  'net-domain': 'GlobeSimple',
  'security-compliance': 'ShieldCheck',
  'sec-secrets': 'Key',
  'design-assets': 'PenNib',
  'design-tools': 'PencilLine',
  'design-ai-image': 'Image',
  'design-ai-3d': 'Cube',
  'design-ai-video': 'VideoCamera',
  'design-digital-human': 'UserCircle',
  'design-ai-music': 'MusicNotes',
  'design-character-rig': 'PersonSimple',
  'design-motion': 'FilmStrip',
  'design-game-assets': 'GameController',
  'design-stock': 'Images',
  'design-inspiration': 'Lightbulb',
  'design-fonts': 'TextT',
  collaboration: 'Kanban',
  'collab-pm': 'Kanban',
  'collab-docs': 'Notebook',
  'collab-suite': 'Buildings',
  globalization: 'GlobeHemisphereWest',
  'global-fx': 'CurrencyCircleDollar',
  'global-entity': 'Buildings',
  'global-i18n': 'Translate',
};

/** 关系类型 -> Phosphor 图标名 */
export const RELATION_ICONS: Record<EdgeType, string> = {
  alternative_to: 'ArrowsLeftRight',
  open_source_alternative_to: 'GitFork',
  domestic_equivalent_of: 'ArrowsClockwise',
  overseas_equivalent_of: 'ArrowsClockwise',
  succeeds: 'ArrowUUpRight',
  deprecated_by: 'Prohibit',
  conflicts_with: 'Warning',
  integrates_with: 'PuzzlePiece',
  compatible_with: 'PuzzlePiece',
  commonly_used_with: 'LinkSimple',
  depends_on: 'TreeStructure',
  powered_by: 'Lightning',
  built_on: 'Cube',
  hosts: 'Cloud',
  provides_access_to: 'Plugs',
  wraps: 'Package',
  part_of: 'PuzzlePiece',
  owned_by: 'Buildings',
  belongs_to_category: 'FolderSimple',
  bundled_in: 'Package',
  implements: 'PlugsConnected',
  supports: 'PlugsConnected',
  uses_concept: 'Lightbulb',
  related_concept: 'Lightbulb',
  prerequisite_of: 'GraduationCap',
  migration_path_to: 'ArrowBendUpRight',
};

/** 常用动作图标 */
export const ACTION_ICONS = {
  search: 'MagnifyingGlass',
  filter: 'Funnel',
  favorite: 'Star',
  follow: 'Bell',
  copy: 'Copy',
  externalLink: 'ArrowSquareOut',
  command: 'Command',
  lock: 'Lock',
  unlock: 'LockOpen',
  key: 'Key',
  sync: 'ArrowsClockwise',
  update: 'Sparkle',
  warning: 'Warning',
  domestic: 'MapPin',
  overseas: 'GlobeSimple',
} as const;
