#!/usr/bin/env python3
"""Wave3 μ：构建工具链、可观测、CI/CD、消息、增长、网络、安全、设计、协作。"""
from __future__ import annotations

REVIEWED = "2026-07-23"


def entry(**kw):
    e = {
        "pricing": {"model": "freemium"},
        "availability": {
            "chinaAccessible": True,
            "needsCompany": False,
            "needsIcp": False,
            "regions": ["global"],
        },
        "tags": [],
        "maturity": "stable",
        "pitfalls": [],
        "updates": [],
        "rankings": [],
        "sources": [],
        "lastReviewed": REVIEWED,
        "region": "overseas",
    }
    e.update(kw)
    if "officialUrl" in e and not e["sources"]:
        e["sources"] = [e["officialUrl"]]
    if e.get("vendorId") is None:
        e.pop("vendorId", None)
    assert len(e["oneLiner"]) <= 60, (e["id"], e["oneLiner"])
    assert len(e.get("descriptionMd", "")) >= 120, (e["id"], len(e.get("descriptionMd", "")))
    assert e.get("pitfalls"), e["id"]
    assert e.get("subcategory"), e["id"]
    return e


def edge(eid, frm, to, typ, weight=0.7, confidence="community", note=None, sources=None):
    e = {"id": eid, "from": frm, "to": to, "type": typ, "weight": weight,
         "confidence": confidence, "sources": sources or [], "createdAt": REVIEWED}
    if note:
        e["note"] = note
    return e


def desc(what, when, caution):
    return f"{what}\n\n{when}\n\n{caution}\n"


def mk(eid, name, cat, sub, one, url, what, when, caution, **extra):
    pitfalls = extra.pop("pitfalls", None)
    kw = {
        "id": eid,
        "name": name,
        "category": cat,
        "subcategory": sub,
        "oneLiner": one,
        "officialUrl": url,
        "descriptionMd": desc(what, when, caution),
        "pitfalls": pitfalls or [caution[:80]],
    }
    kw.update(extra)
    return entry(**kw)


ENTRIES: list[dict] = [
    mk("eslint", "ESLint", "oss-toolchain", "lint",
       "JS/TS 静态分析事实标准", "https://eslint.org",
       "ESLint 是 JavaScript/TypeScript 生态最通用的静态分析引擎，通过可插拔规则与共享配置覆盖代码风格、最佳实践与团队规范。", "存量 React/Vue/Node 项目几乎默认启用；与 Prettier 分工（lint 管逻辑，format 管排版）仍是主流组合。", "规则过多会拖慢 CI；迁移到 Biome/Oxlint 前需盘点自定义插件与 overrides。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['lint', 'javascript'], 'maturity': 'mature'}),
    mk("prettier", "Prettier", "oss-toolchain", "format",
       "固执己见的代码格式化器", "https://prettier.io",
       "Prettier 以「零配置、少争论」著称，统一 TS/JS/CSS/JSON/Markdown 等文件的排版输出，减少 code review 中的格式拉扯。", "团队希望格式化结果完全一致、与 ESLint 解耦时首选；IDE 保存时 format 可显著降低 diff 噪音。", "与 ESLint 格式化规则重叠时易冲突，需 eslint-config-prettier；某些模板字符串/JSX 排版可能不符合个人审美。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['format'], 'maturity': 'mature'}),
    mk("esbuild", "esbuild", "oss-toolchain", "bundler",
       "Go 实现的极速打包与压缩", "https://esbuild.github.io",
       "esbuild 用 Go 编写，提供极快的 TS/JS 打包、压缩与 minify，被 Vite 等工具作为底层依赖广泛采用。", "需要快速 dev/build 反馈、或作为更大工具链的 bundler 内核时优先考虑；适合库打包与简单应用。", "高级 code-splitting、插件生态不如 Rollup/Webpack 完整；复杂 legacy 项目迁移需验证 loader 覆盖。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['bundler', 'build']}),
    mk("turbopack", "Turbopack", "oss-toolchain", "bundler",
       "Next.js 官方 Rust 增量打包器", "https://turbo.build/pack",
       "Turbopack 是 Vercel 用 Rust 开发的增量 bundler，定位为 Webpack 继任者，深度集成 Next.js dev 体验。", "Next.js 15+ 项目追求更快 HMR 与 dev 启动时可启用；与 App Router 同栈选型自然。", "生态与 Webpack 插件不完全兼容；非 Next 项目支持有限，生产构建策略需对照官方文档。",
       **{'vendorId': 'vercel-inc', 'tags': ['bundler', 'nextjs'], 'maturity': 'beta'}),
    mk("webpack", "Webpack", "oss-toolchain", "bundler",
       "最成熟的前端模块打包平台", "https://webpack.js.org",
       "Webpack 通过 loader/plugin 体系支持几乎任意资源类型与复杂构建流水线，是大型存量项目的打包事实标准之一。", "需要精细控制分包、Legacy 浏览器兼容、或已有大量 Webpack 插件投资时继续沿用；微前端与 Module Federation 场景常见。", "配置复杂、冷启动慢；新项目更常选 Vite/Rspack，除非被历史包袱绑定。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['bundler'], 'maturity': 'mature'}),
    mk("vitest", "Vitest", "oss-toolchain", "test",
       "Vite 原生单元测试框架", "https://vitest.dev",
       "Vitest 与 Vite 共享配置与转换管道，提供 Jest 兼容 API、ESM 优先与极快 watch 模式，是 Vite 栈默认测试选择。", "Vite + Vue/React 新项目做单元/组件测试时首选；与 Testing Library 组合覆盖 UI 逻辑。", "Jest 专属 mock/快照边缘行为偶有差异；Monorepo 跨包测试需配置 workspace 别名。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['test', 'vite']}),
    mk("playwright", "Playwright", "oss-toolchain", "test",
       "跨浏览器 E2E 自动化框架", "https://playwright.dev",
       "Playwright 由 Microsoft 维护，支持 Chromium/Firefox/WebKit 并行、自动等待、trace 与 codegen，E2E 与 API 测试一体化。", "需要稳定跨浏览器回归、CI 录屏排障或覆盖登录/支付等关键路径时采用；比 Cypress 更偏多浏览器与并行。", "测试数据与外部依赖需隔离；flaky 用例往往来自时序与网络，应善用 trace 而非盲目加 sleep。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['e2e', 'test'], 'maturity': 'mature'}),
    mk("prisma", "Prisma", "oss-toolchain", "orm",
       "现代 TS ORM 与 schema 工具", "https://www.prisma.io",
       "Prisma 以 schema-first 定义模型，生成类型安全 Client，配套 Migrate 与 Studio，DX 在 TS 全栈中极受欢迎。", "Next.js/Nuxt 等 TS 后端需要强类型数据库访问、快速迭代 schema 时常用；与 PostgreSQL 等搭配多。", "复杂 SQL/窗口函数需回退 raw query；Serverless 连接池要配 Prisma Accelerate 或 PgBouncer。",
       **{'tags': ['orm', 'database']}),
    mk("turbo", "Turborepo", "oss-toolchain", "monorepo",
       "高性能 JS Monorepo 任务编排", "https://turbo.build",
       "Turborepo 提供远程/本地缓存、任务管道与依赖图感知，让 pnpm/yarn workspace 的 build/test/lint 在 CI 中显著加速。", "多包前端/全栈 Monorepo 希望统一脚本与缓存时选用；与 Vercel 集成顺滑。", "缓存键与 env 变量配置不当会导致假绿构建；首次接入需梳理 package 依赖拓扑。",
       **{'vendorId': 'vercel-inc', 'tags': ['monorepo']}),
    mk("nx", "Nx", "oss-toolchain", "monorepo",
       "企业级 Monorepo 与构建图平台", "https://nx.dev",
       "Nx 提供项目图、受影响分析、分布式任务与多框架插件，适合大型多团队仓库治理。", "仓库包数量多、需要 enforce 模块边界与可视化依赖时优于裸 Turborepo；Angular 企业栈常见。", "学习曲线与配置量高于 Turborepo；小团队可能过度工程。",
       **{'tags': ['monorepo'], 'maturity': 'mature'}),
    mk("storybook", "Storybook", "oss-toolchain", "component-dev",
       "组件隔离开发与文档", "https://storybook.js.org",
       "Storybook 在独立环境中渲染 UI 组件 stories，支持交互测试、视觉回归插件与设计系统文档，是组件库标配。", "维护 shadcn/Radix 封装层、设计系统或多主题组件时需要可视化验收与 Chromatic 等视觉 CI。", "版本与 Vite/Webpack 构建器需对齐；stories 过多会拖慢 CI 除非按需构建。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['components', 'docs']}),
    mk("swc", "SWC", "oss-toolchain", "compiler",
       "Rust 实现的 JS/TS 编译器", "https://swc.rs",
       "SWC 用 Rust 提供极快的 TS/JS 转译与压缩，被 Next.js、Rspack 等用作 Babel 替代以缩短构建时间。", "需要 drop Babel 瓶颈、或框架已内置 SWC 时自然采用；也可独立做库打包。", "Babel 宏与部分实验语法插件可能不支持；迁移需跑完整测试矩阵。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['compiler']}),
    mk("oxlint", "Oxlint", "oss-toolchain", "lint",
       "Rust 极速 JS/TS linter", "https://oxc.rs/docs/guide/usage/linter.html",
       "Oxlint 来自 Oxc 项目，以 Rust 实现超快 lint，覆盖大量 ESLint 核心规则，适合作为 CI 第一道门禁。", "超大仓库 lint 成为 CI 瓶颈、或想与 Biome 类似收敛工具链时可试点；常与 ESLint 并存过渡。", "插件生态仍不如 ESLint 完整；自定义规则与 TypeScript 类型感知 lint 能力在演进中。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['lint'], 'maturity': 'beta'}),
    mk("parcel", "Parcel", "oss-toolchain", "bundler",
       "零配置 Web 应用打包器", "https://parceljs.org",
       "Parcel 强调零配置开箱即用，自动处理 HTML/JS/CSS/资源依赖，适合原型与小中型站点快速打包。", "小团队不想维护 Webpack 配置、或教学/demo 项目需要最快上手 bundler 时可选。", "复杂定制与生态小于 Webpack/Vite；大型 Monorepo 场景较少见。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['bundler']}),
    mk("husky", "Husky", "oss-toolchain", "git-hooks",
       "Git hooks 管理工具", "https://typicode.github.io/husky/",
       "Husky 简化 pre-commit/pre-push 等 Git 钩子安装，常与 lint-staged 配合在提交前跑 format/lint/test。", "团队希望把格式与基础检查前移到本地、减少 CI 失败反馈循环时标配。", "钩子过慢会伤害提交体验；应只跑增量 staged 文件，重型 E2E 留给 CI。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['git', 'dx']}),
    mk("changesets", "Changesets", "oss-toolchain", "release",
       "Monorepo 语义化版本发布", "https://github.com/changesets/changesets",
       "Changesets 让贡献者提交变更说明文件，CI 聚合生成版本号与 CHANGELOG，是 pnpm/Turborepo 生态常见发布方案。", "开源或多包 npm 库需要规范 semver 与自动生成 changelog 时采用；比 manual bump 更可审计。", "首次配置 release workflow 需与 npm token/GitHub Actions 权限对齐；ignore 列表要维护。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['release', 'monorepo']}),
    mk("rollup", "Rollup", "oss-toolchain", "bundler",
       "ESM 库打包首选", "https://rollupjs.org",
       "Rollup 专注 ES 模块 tree-shaking 与库打包，输出干净 bundle，是 Vite 生产构建与众多 npm 库的底层选择。", "发布 npm 组件库/工具库、需要多格式输出时首选；插件生态成熟。", "应用级 HMR 不如 Vite 开箱；code-splitting 场景通常交给 Vite/Webpack。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['bundler', 'library'], 'maturity': 'mature'}),
    mk("babel", "Babel", "oss-toolchain", "compiler",
       "JS 语法转译与宏平台", "https://babeljs.io",
       "Babel 通过 preset/plugin 将现代 JS/TS/React 语法转译为目标环境可运行代码，插件生态历史最完整。", "需支持极旧浏览器、或依赖 Babel 宏/特殊插件的 legacy 项目仍离不开；Jest 默认管道也常见。", "构建速度逊于 SWC/esbuild；新项目若无兼容包袱应优先现代 toolchain。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['compiler'], 'maturity': 'mature'}),
    mk("jest", "Jest", "oss-toolchain", "test",
       "Node 生态经典测试框架", "https://jestjs.io",
       "Jest 提供零配置测试、snapshot、mock 与 coverage，长期是 React/Node 项目的默认单元测试框架。", "Create React App 存量、或团队已有大量 Jest 投资时继续沿用；与 Testing Library 组合测 UI。", "ESM 与 TS 配置比 Vitest 繁琐；Monorepo 下 watch 慢时可评估迁移 Vitest。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['test'], 'maturity': 'mature'}),
    mk("cypress", "Cypress", "oss-toolchain", "test",
       "开发者友好的浏览器 E2E", "https://www.cypress.io",
       "Cypress 在真实浏览器中运行 E2E，提供时间旅行调试、截图与 component testing，DX 对前端团队友好。", "单应用 Web 产品、团队以 Chrome 为主做 E2E 且重视调试体验时常见；组件测试可补单元测试盲区。", "多浏览器并行与移动端覆盖不如 Playwright 完整；CI 并行需 Cypress Cloud 或自建编排。",
       **{'tags': ['e2e', 'test']}),
    mk("testing-library", "Testing Library", "oss-toolchain", "test",
       "面向用户行为的测试工具集", "https://testing-library.com",
       "Testing Library 鼓励按角色/文本查询 DOM，避免测试实现细节，覆盖 React/Vue/Svelte 等框架绑定。", "任何需要可维护 UI 单元测试的栈都应采用其查询哲学；与 Jest/Vitest/Playwright 均可配合。", "过度 mock 子组件会失去集成价值；异步 UI 需正确使用 waitFor/findBy。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['test', 'ui']}),
    mk("stylelint", "Stylelint", "oss-toolchain", "lint",
       "CSS/样式静态分析", "https://stylelint.io",
       "Stylelint 对 CSS、SCSS、CSS-in-JS 等做规则检查，可与 Prettier 分工，保障设计 token 与命名一致。", "Tailwind/SCSS 大型项目需要禁止 magic number、统一 BEM 或 enforce 设计规范时启用。", "与 Prettier 规则冲突需单独配置；Tailwind 类名顺序插件会增加 CI 时间。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['lint', 'css']}),
    mk("commitlint", "commitlint", "oss-toolchain", "git-hooks",
       "提交信息规范校验", "https://commitlint.js.org",
       "commitlint 检查 commit message 是否符合 Conventional Commits，便于自动生成 changelog 与语义化版本。", "Monorepo 使用 Changesets/semantic-release、或需要 Jira 关联 ID 时配合 Husky 使用。", "规则过严会阻碍小步提交；可允许 merge/revert 等例外类型。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['git', 'conventions']}),
    mk("lint-staged", "lint-staged", "oss-toolchain", "git-hooks",
       "仅对暂存区跑 lint/format", "https://github.com/lint-staged/lint-staged",
       "lint-staged 在 pre-commit 时只对 git staged 文件执行 ESLint/Prettier 等，避免全仓扫描拖慢提交。", "Husky + lint-staged 是前端团队标配组合；大仓库本地体验提升明显。", "配置 glob 遗漏会导致部分文件绕过检查；与 Monorepo 路径别名要对齐。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['git', 'lint']}),
    mk("tsup", "tsup", "oss-toolchain", "bundler",
       "零配置 TS 库打包", "https://tsup.egoist.dev",
       "tsup 基于 esbuild，为 npm 库提供零配置 ESM/CJS/d.ts 打包，适合工具包与 CLI 快速发布。", "维护小型 TS 开源库、不想手写 Rollup 配置时首选；与 changesets 发布流程契合。", "复杂多入口或自定义插件场景可能需回退 Rollup；类型声明偶需 tsconfig 微调。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['bundler', 'typescript']}),
    mk("rspack", "Rspack", "oss-toolchain", "bundler",
       "Rust 高性能 Webpack 兼容打包", "https://www.rspack.dev",
       "Rspack 由 ByteDance 团队开发，追求 Webpack 配置兼容与 Rust 性能，适合大型前端仓库降本提速。", "Webpack 迁移成本高但 dev/build 太慢时评估 Rspack；与 Module Federation 场景在演进。", "插件 100% 兼容不保证；边缘 loader 行为需回归测试。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['bundler'], 'region': 'both'}),
    mk("rolldown", "Rolldown", "oss-toolchain", "bundler",
       "Rust 版 Rollup/Vite 未来内核", "https://rolldown.rs",
       "Rolldown 是 Vite 团队用 Rust 重写的 bundler，目标统一 dev/prod 管道并进一步提速 Vite 生态。", "跟踪 Vite 6+ 实验特性、或评估下一代 toolchain 时可关注；尚处快速迭代期。", "API 与插件生态仍在建设；生产默认仍应使用成熟 Rollup/esbuild 路径。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['bundler'], 'maturity': 'beta'}),
    mk("npm", "npm", "oss-toolchain", "package-manager",
       "Node 默认包管理器", "https://www.npmjs.com",
       "npm 随 Node.js 分发，提供 registry、CLI 与 workspaces，生态最大但 pnpm 在 Monorepo 性能上更优。", "新手入门、或部署环境只保证 npm 可用时默认选择；npx 跑一次性脚手架仍常用。", "Monorepo 磁盘占用与安装速度不如 pnpm；lockfile 冲突需团队规范 merge 策略。",
       **{'pricing': {'model': 'free'}, 'tags': ['package-manager'], 'maturity': 'mature'}),
    mk("yarn", "Yarn", "oss-toolchain", "package-manager",
       "经典替代 npm 的包管理器", "https://yarnpkg.com",
       "Yarn 提供 Plug'n'Play、workspaces 与 Berry 现代特性，部分企业仓库与开源项目仍深度使用。", "团队历史选型为 Yarn 3+、或需要 PnP 零 node_modules 部署模式时可继续。", "Berry 与部分工具链兼容需插件；新人学习成本高于 pnpm/npm classic。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['package-manager']}),
    mk("knip", "Knip", "oss-toolchain", "analysis",
       "发现未使用依赖与导出", "https://knip.dev",
       "Knip 扫描 JS/TS Monorepo 中 dead files、未使用依赖与 exports，帮助瘦身 package 与加速 CI。", "仓库膨胀、依赖莫名增多或发布前做 bundle 卫生检查时运行；与 TS project references 配合佳。", "动态 import 与框架魔法路由可能误报；首次运行需人工确认再删。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['analysis', 'monorepo']}),
    mk("semantic-release", "semantic-release", "oss-toolchain", "release",
       "全自动语义化发布", "https://semantic-release.gitbook.io",
       "semantic-release 根据 Conventional Commits 自动算版本、生成 notes 并发布 npm/GitHub Release，适合高度自动化流水线。", "开源库维护者希望零手动发版、且 CI 权限可控时采用；与 GitHub Actions 集成成熟。", "配置错误可能意外 major 升级；私有包/registry 凭证管理要严格。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['release', 'ci']}),
    mk("release-please", "release-please", "oss-toolchain", "release",
       "Google 风格 PR 式发版", "https://github.com/googleapis/release-please",
       "release-please 通过 PR 聚合 changelog 与版本 bump，合并后触发 publish，适合需要人工审版本 PR 的团队。", "Monorepo 多包独立版本、或希望 release PR 可 review 时优于全自动 semantic-release。", "首次 manifest 配置繁琐；与 changesets 功能重叠需选型其一。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['release']}),
    mk("renovate", "Renovate", "oss-toolchain", "deps",
       "自动化依赖升级 Bot", "https://docs.renovatebot.com",
       "Renovate 扫描依赖并开 PR 升级，支持 grouping、schedule 与 Monorepo 范围，比 Dependabot 可配置性更强。", "依赖面大的 SaaS/开源项目希望持续安全补丁、又控制 PR 噪音时启用（可限定 major 手动）。", "自动 major 升级可能破坏构建；需配合 CI 与 auto-merge 策略谨慎开启。",
       **{'pricing': {'model': 'freemium'}, 'tags': ['dependencies', 'security']}),
    mk("size-limit", "Size Limit", "oss-toolchain", "analysis",
       "打包体积预算门禁", "https://github.com/andresz1/size-limit",
       "Size Limit 在 CI 中测量 bundle 体积变化，超出预算则失败，防止前端性能回退。", "组件库、营销站或任何关注 FCP 的项目在 PR 阶段 enforce 体积上限。", "仅 gzip 指标可能掩盖 parse 成本；需与 Lighthouse/real user metrics 结合。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['performance', 'ci']}),
    mk("msw", "MSW", "oss-toolchain", "test",
       "API Mock Service Worker", "https://mswjs.io",
       "MSW 在浏览器/Node 拦截网络请求，提供真实 fetch 路径的 mock，适合组件测试与 Storybook。", "前后端并行开发、或 E2E 需稳定 fixture 而不想维护独立 mock server 时使用。", "handlers 与真实 API 漂移会产生假绿；应定期与 OpenAPI 同步或 contract test。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['mock', 'test']}),
    mk("moonrepo", "moon", "oss-toolchain", "monorepo",
       "多语言 Monorepo 任务运行器", "https://moonrepo.dev",
       "moon 提供跨 JS/Rust/Go 等语言的 task graph、caching 与 VCS 钩子，适合 polyglot 仓库。", "Monorepo 不止前端、还含 Rust/Go 服务且希望统一 task 界面时可评估 moon。", "社区小于 Nx/Turbo；插件与文档深度需团队自行验证。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['monorepo']}),
    mk("datadog", "Datadog", "obs-platform", "apm",
       "云原生 APM 与基础设施监控", "https://www.datadoghq.com",
       "Datadog 整合 metrics、logs、traces、RUM 与安全信号，提供统一可观测平台与丰富集成，SaaS 交付免运维。", "多服务微架构、需要 correlate 指标/日志/链路并做 SLO 告警时首选；与 Kubernetes/Docker 集成成熟。", "按 host/container 计费易膨胀；国内访问与数据合规需评估 region 与代理。",
       **{'vendorId': 'datadog-inc', 'tags': ['apm', 'metrics'], 'pricing': {'model': 'usage'}}),
    mk("betterstack", "Better Stack", "obs-errors", "uptime",
       "日志、告警与状态页一体化", "https://betterstack.com",
       "Better Stack（原 Logtail）提供日志采集、异常告警、On-call 与公开状态页，界面现代、上手快。", "中小团队希望替代 Datadog 部分能力、快速搭 status page 与日志检索时可选。", "高级 APM 与自定义 metric 能力弱于 Datadog；大规模日志 retention 成本需预算。",
       **{'vendorId': 'betterstack-inc', 'tags': ['logging', 'uptime']}),
    mk("prometheus", "Prometheus", "obs-platform", "metrics",
       "云原生指标采集与告警", "https://prometheus.io",
       "Prometheus 拉取式 metrics 存储与 PromQL 查询是 CNCF 标准，常与 Grafana 搭配做自建可观测。", "Kubernetes 自建监控、或需要完全掌控 metrics 管道与告警规则时采用；适合 SRE 团队。", "长期存储与高基数 cardinality 需 Thanos/VictoriaMetrics；运维复杂度高于 SaaS。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['metrics', 'kubernetes'], 'maturity': 'mature'}),
    mk("newrelic", "New Relic", "obs-platform", "apm",
       "全栈 APM 与数字体验监控", "https://newrelic.com",
       "New Relic 提供应用性能、基础设施、浏览器与 mobile RUM，一体化 dashboard 适合快速定位慢查询与错误。", "需要开箱即用 APM、又不想自建 Prometheus 栈的 SaaS 团队；Node/Java 支持成熟。", "定价按 ingest 计费易超预期；国内网络访问可能不稳定。",
       **{'vendorId': 'newrelic-inc', 'tags': ['apm', 'rum']}),
    mk("highlight-io", "Highlight.io", "obs-errors", "session-replay",
       "开源会话回放与错误监控", "https://www.highlight.io",
       "Highlight.io 结合 session replay、错误追踪与 logs，开源可自托管，对前端 bug 复现友好。", "前端团队需要「看见用户如何触发错误」、预算有限不想 FullStory 时评估。", "自托管资源消耗大；与后端 trace 关联需额外集成 OpenTelemetry。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['session-replay', 'errors']}),
    mk("honeycomb", "Honeycomb", "obs-platform", "tracing",
       "高基数事件分析与调试", "https://www.honeycomb.io",
       "Honeycomb 面向高 cardinality 事件数据，帮助调试分布式系统中「难以聚合」的边缘 case，BubbleUp 异常检测有特色。", "微服务体量大、传统 metrics 难以回答 ad-hoc 问题时采用；SRE 深度调试场景。", "学习曲线与数据建模要求高；国内直连与账单需提前验证。",
       **{'vendorId': 'honeycomb-io', 'tags': ['tracing', 'debug']}),
    mk("loki", "Grafana Loki", "obs-platform", "logging",
       "Prometheus 风格的日志聚合", "https://grafana.com/oss/loki/",
       "Grafana Loki 只索引 labels 不索引全文，低成本集中 logs，与 Grafana/Prometheus 同栈自然。", "已用 Grafana 栈、希望 logs 与 metrics 同 UI 且控制存储成本时选用。", "全文检索能力弱于 ELK；label 设计不当会导致查询困难或 hot shard。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['logging', 'grafana']}),
    mk("jaeger", "Jaeger", "obs-platform", "tracing",
       "分布式链路追踪系统", "https://www.jaegertracing.io",
       "Jaeger 是 CNCF 分布式 tracing 项目，支持 OpenTelemetry，适合可视化跨服务调用链与延迟瓶颈。", "自建 K8s 可观测、或已标准化 OpenTelemetry 导出时需要 trace backend。", "生产级存储需 Elasticsearch/Cassandra 等；UI 功能不如商业 APM 丰富。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['tracing', 'opentelemetry']}),
    mk("signoz", "SigNoz", "obs-platform", "apm",
       "开源 OpenTelemetry APM", "https://signoz.io",
       "SigNoz 是基于 OTel 的开源 APM，提供 traces/metrics/logs 统一 UI，可自托管替代 Datadog 部分场景。", "希望 OTel 原生、数据自主可控且预算有限的中型团队可评估 SigNoz Cloud 或自托管。", "功能深度与集成数量仍在追赶商业产品；升级与备份需自行运维。",
       **{'tags': ['opentelemetry', 'apm']}),
    mk("bugsnag", "Bugsnag", "obs-errors", "error-tracking",
       "移动端与 Web 错误监控", "https://www.bugsnag.com",
       "Bugsnag 专注 crash/error 聚合、release 健康度与 breadcrumbs，移动端 SDK 成熟。", "React Native/移动 App 需要稳定 crash 报告与 release 对比时常见选型。", "session replay 与 infra 监控非强项；与 Sentry 功能重叠需对比定价。",
       **{'vendorId': 'bugsnag-inc', 'tags': ['errors', 'mobile']}),
    mk("rollbar", "Rollbar", "obs-errors", "error-tracking",
       "实时错误聚合与告警", "https://rollbar.com",
       "Rollbar 收集前后端异常、分组 dedupe 并联动 Slack/PagerDuty，适合快速接入的错误监控。", "已有应用需轻量 error tracking、重视告警路由与 deploy tracking 时可选。", "RUM 与性能监控能力有限；国内访问速度一般。",
       **{'vendorId': 'rollbar-inc', 'tags': ['errors']}),
    mk("logrocket", "LogRocket", "obs-product", "session-replay",
       "前端会话回放与产品洞察", "https://logrocket.com",
       "LogRocket 录制用户会话、控制台与网络请求，帮助产品/工程定位 UX 问题与转化漏斗异常。", "SaaS 产品需要 qualitative 数据补 quantitative analytics 时采用；与 GA4 互补。", "隐私合规（GDPR/录音遮罩）配置必须严谨；大流量账单显著。",
       **{'vendorId': 'logrocket-inc', 'tags': ['session-replay', 'product']}),
    mk("openreplay", "OpenReplay", "obs-product", "session-replay",
       "可自托管的开源会话回放", "https://openreplay.com",
       "OpenReplay 提供开源 session replay、co-browsing 与 devtools 式调试，可完全私有部署。", "对数据驻留有要求、又需要 LogRocket 类能力时首选自托管路径。", "部署与存储成本不低；移动端支持仍在完善。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['session-replay']}),
    mk("tempo", "Grafana Tempo", "obs-platform", "tracing",
       "低成本 trace 存储后端", "https://grafana.com/oss/tempo/",
       "Grafana Tempo 与 Loki/Mimir 同理念，专注 trace 存储与 Grafana 关联，适合 OTel trace 长期留存。", "Grafana 全家桶用户希望 traces 与 logs/metrics 一键跳转关联时接入 Tempo。", "独立使用价值有限；需配合 OTel collector 与 Grafana。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['tracing']}),
    mk("elastic-apm", "Elastic APM", "obs-platform", "apm",
       "Elastic 栈内置 APM", "https://www.elastic.co/observability/application-performance-monitoring",
       "Elastic APM 与 Elasticsearch/Kibana 集成，提供应用性能、日志与 SIEM 统一检索，适合已投资 Elastic 的团队。", "企业已部署 ELK/Elastic Cloud、希望 APM 与日志同集群检索时自然扩展。", "资源占用高于轻量 OTel backend；license 变更需关注。",
       **{'vendorId': 'elastic-inc', 'tags': ['apm', 'elasticsearch']}),
    mk("dynatrace", "Dynatrace", "obs-platform", "apm",
       "AI 驱动的企业 APM", "https://www.dynatrace.com",
       "Dynatrace 提供自动拓扑发现、AI 根因分析与 infra 监控，面向大型企业全栈可观测。", "金融/电信等大型企业需要 auto-discovery 与合规审计级 APM 时评估。", "价格与实施成本高；中小团队通常 overkill。",
       **{'vendorId': 'dynatrace-inc', 'tags': ['apm', 'enterprise']}),
    mk("glitchtip", "Glitchtip", "obs-errors", "error-tracking",
       "Sentry 兼容的开源错误追踪", "https://glitchtip.com",
       "Glitchtip 实现 Sentry 协议子集，可自托管错误监控，适合希望降低 Sentry 账单的场景。", "已有 Sentry SDK 集成、但希望私有化部署或轻量替代时可迁移评估。", "功能与性能不及官方 Sentry；部分 SDK 特性可能不兼容。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['errors', 'self-hosted']}),
    mk("gitlab-ci", "GitLab CI/CD", "cicd-pipeline", "ci",
       "与 GitLab 一体的 CI/CD", "https://docs.gitlab.com/ee/ci/",
       "GitLab CI 在单一平台提供 repo、MR、CI pipeline、容器 registry 与 deploy，适合希望减少工具碎片的企业。", "已用 GitLab 托管代码、或需要 self-hosted 一体化 DevOps 平台时默认启用 CI。", "Runner 维护与 artifact 存储成本需规划；复杂 pipeline  YAML 可读性挑战大。",
       **{'vendorId': 'gitlab-inc', 'tags': ['ci', 'git']}),
    mk("kubernetes", "Kubernetes", "cicd-pipeline", "orchestration",
       "容器编排事实标准", "https://kubernetes.io",
       "Kubernetes 编排容器化工作负载，提供声明式部署、服务发现、自动伸缩与 rolling update，云原生基础设施核心。", "微服务上云、需要 portable 编排且团队有 SRE 能力时采用；与 Helm/Argo 生态丰富。", "学习曲线陡峭；小项目直接 PaaS（Railway/Fly）可能更省运维。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['containers', 'orchestration'], 'maturity': 'mature'}),
    mk("terraform", "Terraform", "cicd-pipeline", "iac",
       "基础设施即代码工具", "https://www.terraform.io",
       "Terraform 用 HCL 描述云资源，plan/apply 工作流支持多云与模块复用，是 IaC 领域最普及的选择之一。", "需要版本化基础设施、多环境（dev/staging/prod）一致性与 PR review infra 变更时采用。", "state 文件管理与 drift 检测需规范；Terraform Cloud 与 OpenTofu 分叉需关注许可证。",
       **{'vendorId': 'hashicorp', 'tags': ['iac', 'cloud'], 'maturity': 'mature'}),
    mk("circleci", "CircleCI", "cicd-pipeline", "ci",
       "云 CI 平台", "https://circleci.com",
       "CircleCI 提供可扩展 Docker/VM executor、orbs 复用与并行测试，与 GitHub/GitLab 集成成熟。", "需要比 GitHub Actions 更强并行与缓存、或混合 cloud/self-hosted runner 时选用。", "免费额度有限；复杂 workflow 调试不如本地 act 方便。",
       **{'vendorId': 'circleci-inc', 'tags': ['ci']}),
    mk("buildkite", "Buildkite", "cicd-pipeline", "ci",
       "Agent 式弹性 CI", "https://buildkite.com",
       "Buildkite 控制面在云端、runner 自建，适合需要隔离构建环境与安全合规的企业。", "构建需访问内网资源、或希望 CI 算力完全自控时优于纯 SaaS runner。", "需自行维护 agent 池；pipeline 语法与 GitHub Actions 不同需迁移成本。",
       **{'vendorId': 'buildkite-inc', 'tags': ['ci', 'self-hosted']}),
    mk("argo-cd", "Argo CD", "cicd-pipeline", "cd",
       "GitOps 持续交付", "https://argo-cd.readthedocs.io",
       "Argo CD 监控 Git 仓库 manifest 与集群状态差异，自动/手动 sync，是 Kubernetes GitOps 主流方案。", "K8s 部署希望以 Git 为唯一真相源、可审计 rollback 时采用；与 Helm/Kustomize 配合。", "Application 配置复杂时 diff 难读；多集群联邦需额外架构。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['gitops', 'kubernetes']}),
    mk("earthly", "Earthly", "cicd-pipeline", "build",
       "可复现的容器化构建", "https://earthly.dev",
       "Earthly 用 Earthfile 封装 build/test，本地与 CI 同一命令可复现，减少「CI 才失败」问题。", "Monorepo 构建脚本分散在 Makefile/CI YAML 中难以维护时统一为 Earthfile。", "额外抽象层增加学习成本；生态小于原生 Docker BuildKit。",
       **{'tags': ['build', 'reproducible']}),
    mk("nixpacks", "Nixpacks", "cicd-pipeline", "buildpack",
       "零配置容器构建", "https://nixpacks.com",
       "Nixpacks 由 Railway 维护，自动检测语言并生成 OCI 镜像，类似 Cloud Native Buildpacks 但更简单。", "Railway/Fly 等 PaaS 用户希望免 Dockerfile 部署常见栈时默认路径。", "定制性不如手写 Dockerfile； exotic 依赖可能检测失败。",
       **{'vendorId': 'railway-app', 'tags': ['buildpack', 'docker']}),
    mk("ansible", "Ansible", "cicd-pipeline", "config",
       "无 agent 的配置管理", "https://www.ansible.com",
       "Ansible 通过 SSH 推送 playbook 配置服务器、安装软件与编排滚动发布，适合传统 VM 与混合环境。", "仍有大量 bare-metal/VM 运维、或 K8s 之外需要配置管理时采用。", "大规模动态 inventory 性能不如 Chef/Puppet 历史方案；idempotency 测试需 discipline。",
       **{'vendorId': 'red-hat', 'tags': ['config', 'automation'], 'maturity': 'mature'}),
    mk("jenkins", "Jenkins", "cicd-pipeline", "ci",
       "可插件化的经典 CI 服务器", "https://www.jenkins.io",
       "Jenkins 通过海量插件集成几乎任何工具链，支持 self-hosted pipeline，存量企业安装基盘大。", "遗留 pipeline 已深度绑定 Jenkins、或必须完全内网 CI 时可继续维护。", "UI 老旧、插件安全与升级痛苦；新项目优先 GitHub Actions/GitLab CI。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['ci', 'legacy'], 'maturity': 'mature'}),
    mk("tekton", "Tekton", "cicd-pipeline", "ci",
       "Kubernetes 原生 CI/CD", "https://tekton.dev",
       "Tekton 在 K8s 上以 CRD 定义 Task/Pipeline，cloud-native CI 可随集群伸缩，与 Argo 互补。", "CI 工作负载希望与 K8s 调度统一、或构建本身需要大量弹性算力时采用。", "YAML 冗长；本地调试体验不如 Docker-based CI。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['kubernetes', 'ci']}),
    mk("flux-cd", "Flux CD", "cicd-pipeline", "cd",
       "GitOps 工具链（CNCF）", "https://fluxcd.io",
       "Flux CD 持续 reconcile 集群与 Git 源，支持 Helm/Kustomize，与 Argo CD 同为 GitOps 主流，更偏 GitOps Toolkit 模块化。", "偏好 CNCF 项目、或需要多 tenant GitOps 控制器时评估 Flux vs Argo。", "Argo UI 更成熟；团队需选型统一以免双轨运维。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['gitops']}),
    mk("helm", "Helm", "cicd-pipeline", "packaging",
       "Kubernetes 包管理器", "https://helm.sh",
       "Helm 用 chart 模板化 K8s manifest，支持版本 release 与 rollback，是 K8s 应用分发事实标准。", "部署第三方中间件或内部 microservice 到 K8s 时几乎必用；与 Argo/Flux 集成。", "chart 值过多导致 override 复杂；secret 管理勿明文进 values。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['kubernetes'], 'maturity': 'mature'}),
    mk("packer", "Packer", "cicd-pipeline", "iac",
       "多平台镜像构建", "https://www.packer.io",
       "Packer 从单一配置构建 AMI/OCI/Docker 等镜像，适合 golden image 流水线与混合云。", "仍需 VM 而非容器、或需要标准化 OS 镜像供 Terraform 消费时采用。", "镜像 pipeline 维护成本；云厂商原生 image builder 可能更简单。",
       **{'vendorId': 'hashicorp', 'tags': ['images', 'iac']}),
    mk("dagger", "Dagger", "cicd-pipeline", "build",
       "可移植的 CI 管道 SDK", "https://dagger.io",
       "Dagger 用 Python/Go/TS 编写 pipeline，在本地容器与 CI 中同一套代码运行，解决 shell YAML 难测试问题。", "希望 pipeline 可单元测试、跨 GitHub/GitLab CI 复用时评估 Dagger。", "相对新、生态小；团队需接受 SDK 范式 shift。",
       **{'tags': ['ci', 'sdk']}),
    mk("sendgrid", "SendGrid", "msg-email", "transactional",
       "Twilio 旗下事务邮件 API", "https://sendgrid.com",
       "SendGrid 提供 SMTP/API 发送事务与营销邮件，模板、统计与送达率工具成熟，开发者接入广。", "产品需要 signup/reset password 等事务邮件且希望快速 API 集成时常见；与 Twilio 生态统一。", "共享 IP 信誉影响送达；高量需 dedicated IP 与域名认证（SPF/DKIM/DMARC）。",
       **{'vendorId': 'twilio-inc', 'tags': ['email', 'transactional']}),
    mk("postmark", "Postmark", "msg-email", "transactional",
       "专注事务邮件的 ESP", "https://postmarkapp.com",
       "Postmark 只做事务邮件，强调极速送达与清晰 bounce 处理，营销邮件功能刻意弱化以保证信誉。", "SaaS 事务邮件量大、对 inbox 率敏感且不需要营销 blast 时优于 SendGrid。", "不支持营销活动；价格随量上升需对比 AWS SES。",
       **{'vendorId': 'activecampaign', 'tags': ['email', 'transactional']}),
    mk("aws-ses", "Amazon SES", "msg-email", "transactional",
       "AWS 低成本邮件发送", "https://aws.amazon.com/ses/",
       "Amazon Simple Email Service 按量计费发送邮件，与 AWS 生态集成，适合已在 AWS 上的团队。", "基础设施在 AWS、邮件量中大且希望成本可控时首选；可用 Lambda 触发。", "初始 sandbox 限制严；送达率需自行 warm-up 与监控 reputation。",
       **{'vendorId': 'amazon', 'tags': ['email', 'aws'], 'region': 'overseas'}),
    mk("aliyun-directmail", "阿里云邮件推送", "msg-email", "transactional",
       "国内事务邮件与通知", "https://www.aliyun.com/product/directmail",
       "阿里云 DirectMail 提供国内合规的事务邮件与批量通知，控制台与 API 对接阿里云生态，适合备案站点。", "面向国内用户的发票、验证码、运营通知且服务器在阿里云时选用。", "海外收件送达与模板审核规则需单独确认；营销与事务通道要分离。",
       **{'vendorId': 'aliyun', 'tags': ['email'], 'region': 'domestic'}),
    mk("aliyun-sms", "阿里云短信", "msg-sms", "transactional",
       "国内短信验证码与通知", "https://www.aliyun.com/product/sms",
       "阿里云短信服务提供模板短信、验证码与营销短信，签名与模板需工信部备案审核，控制台支持发送统计与失败重试。", "国内 App/网站 OTP、物流通知与运营短信标配；与阿里云 ECS/OSS 等同账号账单统一，便于财务对账。", "模板审核周期长；营销短信通道与事务通道费率不同，勿混用以免触发运营商拦截。",
       **{'vendorId': 'aliyun', 'tags': ['sms'], 'region': 'domestic'}),
    mk("tencent-sms", "腾讯云短信", "msg-sms", "transactional",
       "腾讯云短信与营销通道", "https://cloud.tencent.com/product/sms",
       "腾讯云 SMS 支持国内国际短信、模板管理与发送统计，控制台可配置回调与配额告警，与微信生态企业常见组合。", "业务已在腾讯云、或需与小程序/企微同一账号体系时选用；跨境业务可评估国际短信路由。", "国际短信路由与到达率因国家而异；需监控失败码、频率限制与签名合规，避免批量发送被封。",
       **{'vendorId': 'tencent-cloud', 'tags': ['sms'], 'region': 'domestic'}),
    mk("jpush", "极光推送", "msg-push", "mobile-push",
       "国内 Android/iOS 推送聚合", "https://www.jiguang.cn/push",
       "极光推送 JPush 是国内常用的移动 push SDK，支持多厂商通道聚合，提升 Android 到达率。", "面向国内用户的移动 App 需要稳定 push 且需适配各厂商通道时首选国内方案。", "海外 push 能力有限；隐私合规与用户同意弹窗必须到位。",
       **{'vendorId': 'jiguang', 'tags': ['push', 'mobile'], 'region': 'domestic'}),
    mk("getui", "个推", "msg-push", "mobile-push",
       "国内智能推送与用户运营", "https://www.getui.com",
       "个推提供 push、用户画像与增长工具，在国内 Android 厂商通道聚合与到达率方面有长期积累，控制台支持分群与 A/B。", "需要 push 之外轻量用户运营、或已与个推 SDK 历史集成时继续；适合国内 Android 占比高的 App。", "文档与控制台偏国内语境；国际化产品需评估海外节点、隐私政策与用户同意流程是否满足当地法规。",
       **{'vendorId': 'getui-inc', 'tags': ['push'], 'region': 'domestic'}),
    mk("onesignal", "OneSignal", "msg-push", "mobile-push",
       "跨平台 push 与消息中心", "https://onesignal.com",
       "OneSignal 支持 mobile/web push、in-app messaging 与 email 统一编排，免费层慷慨。", "全球化 App 需要 web+mobile push、或希望免自建 FCM/APNs 封装时选用。", "高级 segmentation 与 Journeys 需付费；国内 Android 厂商通道需额外配置。",
       **{'vendorId': 'onesignal-inc', 'tags': ['push', 'web']}),
    mk("slack", "Slack", "msg-im", "team-chat",
       "团队即时通讯与集成 hub", "https://slack.com",
       "Slack 提供频道、thread、workflow 与海量第三方集成，是海外工程/产品团队默认协作 IM。", "远程团队日常沟通、CI 通知与 bot 集成（Sentry/Linear）时核心工具。", "免费版消息历史有限；国内访问不稳定需考虑飞书/企微替代。",
       **{'vendorId': 'salesforce', 'tags': ['chat', 'integrations']}),
    mk("discord", "Discord", "msg-im", "community",
       "社区与开发者聊天平台", "https://discord.com",
       "Discord 提供 server/channel、voice 与 bot API，开源社区、游戏与 Web3 项目常用作用户社区 hub。", "需要运营公开社区、voice activity 或 bot 机器人生态时选用 Discord 而非 Slack。", "不适合严肃企业内部合规 IM；消息留存与审计能力弱。",
       **{'vendorId': 'discord-inc', 'tags': ['community', 'chat']}),
    mk("telegram-bot", "Telegram Bot API", "msg-im", "bot",
       "Bot 优先的 IM 平台 API", "https://core.telegram.org/bots/api",
       "Telegram Bot API 让开发者构建 bot 做通知、客服与 mini-app，全球可达、无需手机验证即可测试。", "面向国际用户的 alert bot、crypto/工具类产品通知通道时常见；与 serverless 易集成。", "国内访问不稳定；不适合作为主事务通知唯一通道。",
       **{'tags': ['bot', 'api'], 'pricing': {'model': 'free'}}),
    mk("dingtalk", "钉钉", "msg-im", "enterprise",
       "国内企业 IM 与办公套件", "https://www.dingtalk.com",
       "钉钉提供 IM、审批、考勤、文档与开放 API，是国内企业数字化与机器人通知的主流平台之一。", "国内团队内部协作、OA 审批与阿里云/DevOps 机器人告警时默认选项。", "与飞书/企微并存时易造成工具分裂；开放平台 rate limit 需规划。",
       **{'vendorId': 'alibaba', 'tags': ['enterprise', 'chat'], 'region': 'domestic'}),
    mk("microsoft-teams", "Microsoft Teams", "msg-im", "enterprise",
       "Microsoft 365 团队聊天", "https://www.microsoft.com/microsoft-teams",
       "Teams 与 Office/Azure AD 深度集成，提供 chat、meetings 与 app tab，是企业 Microsoft 栈协作中心。", "公司已标准化 M365/Azure AD、或政企采购 Microsoft 协议时默认 IM。", "Guest 体验与 channel 管理复杂；非 Microsoft 栈团队集成成本高。",
       **{'vendorId': 'microsoft', 'tags': ['enterprise', 'chat']}),
    mk("mattermost", "Mattermost", "msg-im", "self-hosted",
       "开源 Slack 替代", "https://mattermost.com",
       "Mattermost 可自托管 team chat，支持 compliance 与 plugin，适合对数据驻留有要求的组织。", "金融/政府等不能直接 SaaS IM、又想要 Slack 体验时自托管 Mattermost。", "插件与 UX 不如 Slack  polished；运维 HA 与升级需专职。",
       **{'tags': ['chat', 'self-hosted']}),
    mk("mailgun", "Mailgun", "msg-email", "transactional",
       "开发者导向邮件 API", "https://www.mailgun.com",
       "Mailgun 提供 REST API 发送/接收邮件、路由与验证，在欧洲有数据中心，开发者文档清晰。", "欧洲数据驻留、或需要 inbound parse webhooks 处理回复邮件时评估 Mailgun。", "与 SendGrid 功能重叠；国内送达率非优势。",
       **{'vendorId': 'sinch', 'tags': ['email']}),
    mk("brevo", "Brevo", "msg-email", "marketing",
       "邮件+SMS 营销自动化", "https://www.brevo.com",
       "Brevo（原 Sendinblue）合并事务邮件、营销 automation 与 SMS，欧洲 GDPR 友好，定价透明。", "欧盟用户为主、需要邮件+SMS 一体营销且预算中等时可选。", "事务送达专注度不如 Postmark；模板编辑器学习曲线存在。",
       **{'vendorId': 'brevo-inc', 'tags': ['email', 'marketing']}),
    mk("apns", "Apple Push Notification", "msg-push", "mobile-push",
       "iOS/macOS 原生推送通道", "https://developer.apple.com/documentation/usernotifications",
       "APNs 是 Apple 官方 push 服务，任何 iOS App 后台通知必须经 APNs 或聚合 SDK 间接接入。", "自研 iOS push 或选择 OneSignal 等时需理解 APNs 证书/key 轮换与 topic 配置。", "证书管理易出错导致全量 push 失败；Development/Production 环境勿混用。",
       **{'vendorId': 'apple', 'tags': ['push', 'ios']}),
    mk("zulip", "Zulip", "msg-im", "team-chat",
       "线程化开源团队聊天", "https://zulip.com",
       "Zulip 以 topic thread 组织对话，减少 Slack 式 channel 噪音，开源可自托管，适合工程团队异步协作。", "偏好 thread-first 讨论、或希望自托管且比 Mattermost 更强调话题结构时选用。", "移动端与集成数量少于 Slack；用户习惯迁移需培训。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['chat']}),
    mk("mixpanel", "Mixpanel", "growth-web", "product-analytics",
       "事件驱动产品分析", "https://mixpanel.com",
       "Mixpanel 以 event-based 分析漏斗、留存与 cohort，适合产品团队回答「用户做了什么」而非仅页面浏览。", "SaaS 需要细粒度行为分析、A/B 与 feature adoption 跟踪时常用；与 GA4 互补。", "implementation 需 disciplined event schema；MTU 计费易膨胀。",
       **{'vendorId': 'mixpanel-inc', 'tags': ['analytics', 'product']}),
    mk("amplitude", "Amplitude", "growth-web", "product-analytics",
       "产品智能与实验平台", "https://amplitude.com",
       "Amplitude 提供行为分析、experiment 与 CDP 能力，面向 growth 与 product 一体化数据平台。", "需要 experimentation + analytics 同一 vendor、或复杂 user journey 分析时评估 Amplitude。", "国内直连与数据合规需确认；小项目可能 overkill。",
       **{'vendorId': 'amplitude-inc', 'tags': ['analytics', 'experiments']}),
    mk("sensorsdata", "神策数据", "growth-web", "product-analytics",
       "国内私有化产品分析", "https://www.sensorsdata.cn",
       "神策数据提供 SDK 采集、用户画像、漏斗与个性化推荐，支持私有化部署与混合云，金融与零售头部客户案例多。", "国内企业对数据不出域有强合规、需要专业实施与本地化支持的产品分析时首选国内方案。", "实施与 license 成本高；跨境产品需单独评估海外采集节点与 GDPR/PIPL 双合规策略。",
       **{'vendorId': 'sensorsdata', 'tags': ['analytics'], 'region': 'domestic'}),
    mk("growingio", "GrowingIO", "growth-web", "product-analytics",
       "无埋点与国内增长分析", "https://www.growingio.com",
       "GrowingIO 强调无埋点采集与可视化圈选，适合快速上线行为分析、热图与留存报表，国内增长团队中文文档完善。", "希望减少手动埋点成本、主要用户在国内且需中文支持与本地实施伙伴时选用 GrowingIO。", "复杂漏斗与精细 event schema 仍可能需要代码埋点；被收购后产品路线图与定价需持续关注。",
       **{'vendorId': 'growingio', 'tags': ['analytics'], 'region': 'domestic'}),
    mk("ahrefs", "Ahrefs", "growth-web", "seo",
       "SEO 工具与外链分析", "https://ahrefs.com",
       "Ahrefs 提供关键词研究、站点审计、外链监控与 rank tracking，是 SEO 从业者常用 premium 工具。", "内容营销与 SEO 驱动增长、需要 competitive backlink 情报时投资 Ahrefs。", "价格偏高；仅适合 SEO 是核心渠道的团队。",
       **{'vendorId': 'ahrefs-inc', 'tags': ['seo']}),
    mk("google-search-console", "Google Search Console", "growth-web", "seo",
       "Google 搜索表现官方工具", "https://search.google.com/search-console",
       "Search Console 展示站点在 Google 搜索的展示、点击、索引覆盖与 Core Web Vitals，免费且权威。", "任何依赖 Google 自然流量的站点都应配置并监控 GSC；与 GA4 关联。", "仅覆盖 Google；Bing/百度需另配工具。",
       **{'vendorId': 'google', 'tags': ['seo'], 'pricing': {'model': 'free'}}),
    mk("microsoft-clarity", "Microsoft Clarity", "growth-web", "behavior-analytics",
       "免费热图与会话录制", "https://clarity.microsoft.com",
       "Clarity 提供 heatmap、session recording 与 insight，完全免费，适合轻量 UX 定性分析。", "预算有限但需要 Hotjar 类热图、且主要流量在桌面/移动 web 时启用。", "数据保留与 GDPR 需配置 masking；高流量站点可能有采样。",
       **{'vendorId': 'microsoft', 'tags': ['heatmap'], 'pricing': {'model': 'free'}}),
    mk("hotjar", "Hotjar", "growth-web", "behavior-analytics",
       "热图、录屏与反馈 widget", "https://www.hotjar.com",
       "Hotjar 整合 heatmaps、recordings、surveys 与 feedback，帮助优化 landing 与 onboarding UX。", "营销/产品需要快速看懂页面互动、收集 on-site 反馈时选用。", "免费层 session 有限；与 Clarity 功能重叠可二选一。",
       **{'vendorId': 'hotjar-inc', 'tags': ['heatmap', 'ux']}),
    mk("matomo", "Matomo", "growth-web", "web-analytics",
       "开源可自托管网站分析", "https://matomo.org",
       "Matomo（原 Piwik）提供 GDPR 友好、可自托管的 web analytics，替代 GA 以保留数据主权。", "欧盟或隐私敏感场景不愿将数据给 Google、又需要 classic analytics 报告时采用。", "自托管运维与升级成本；插件生态小于 GA4。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['analytics', 'privacy']}),
    mk("segment", "Segment", "growth-web", "cdp",
       "客户数据平台与事件路由", "https://segment.com",
       "Segment 统一采集 SDK 并将 events 路由到 Mixpanel/GA/BigQuery 等，减少多处埋点重复。", "多下游 analytics/marketing 工具、需要 one SDK many destinations 时采用 Segment。", "Twilio 收购后定价变化需关注；简单站点直接 GA4 即可。",
       **{'vendorId': 'twilio-inc', 'tags': ['cdp', 'analytics']}),
    mk("semrush", "Semrush", "growth-web", "seo",
       "SEO/SEM 竞争情报套件", "https://www.semrush.com",
       "Semrush 覆盖关键词、广告研究、内容工具与 site audit，偏 marketing ops 全栈而非纯 backlink。", "需要 SEO+PPC+内容一体化 toolkit、与 agency 协作时常见。", "与 Ahrefs 功能重叠；订阅档位多需选对 plan。",
       **{'vendorId': 'semrush-inc', 'tags': ['seo', 'marketing']}),
    mk("heap", "Heap", "growth-web", "product-analytics",
       "自动捕获分析与 retroactive 漏斗", "https://www.heap.io",
       "Heap 自动 capture 前端事件，支持 retroactive 定义 funnel，减少 upfront 埋点规划。", "产品迭代快、来不及设计 event taxonomy 又需要分析历史行为时评估 Heap。", "自动采集噪声大；PII 过滤与 GDPR 配置必须严格。",
       **{'vendorId': 'heap-inc', 'tags': ['analytics', 'autocapture']}),
    mk("fathom", "Fathom Analytics", "growth-web", "web-analytics",
       "隐私优先的轻量网站统计", "https://usefathom.com",
       "Fathom 提供简单、无 cookie banner 需求的 analytics（视 jurisdiction），页面级 PV 与 referrers，极简 UI。", "个人站/小型 SaaS 需要比 Plausible 更极简、重视隐私营销叙事时可选。", "无深度 product analytics；复杂 funnel 请用 Mixpanel。",
       **{'vendorId': 'fathom-inc', 'tags': ['analytics', 'privacy']}),
    mk("namecheap", "Namecheap", "net-domain", "registrar",
       "平价域名注册与 DNS", "https://www.namecheap.com",
       "Namecheap 提供域名注册、WhoisGuard 与基础 DNS，价格透明，个人与 indie hacker 常用。", "注册 .com/.dev 等新项目域名、需要便宜 SSL 与 DNS 托管时首选之一。", "高级 DNS 功能不如 Cloudflare；转移锁与 auto-renew 要确认。",
       **{'vendorId': 'namecheap-inc', 'tags': ['domain']}),
    mk("porkbun", "Porkbun", "net-domain", "registrar",
       "低价域名与透明定价", "https://porkbun.com",
       "Porkbun 以低 renewal 价格与免费 WHOIS privacy 著称，UI 现代，受开发者社区喜爱。", "希望降低域名长期持有成本、注册 odd TLD 时可选 Porkbun。", "企业级 support 与 bulk 工具不如 GoDaddy；国内支付手段有限。",
       **{'vendorId': 'porkbun-inc', 'tags': ['domain']}),
    mk("cloudflare-registrar", "Cloudflare Registrar", "net-domain", "registrar",
       "At-cost 域名注册", "https://www.cloudflare.com/products/registrar/",
       "Cloudflare Registrar 按成本价卖域名，与 Cloudflare DNS/CDN 同一账号，转移与 DNSSEC 流程顺滑。", "已全站 Cloudflare、希望域名与 CDN/WAF 统一账单与管理时注册于此。", "可注册 TLD 列表小于 Namecheap；需先用 Cloudflare DNS 才能转 registrar。",
       **{'vendorId': 'cloudflare-inc', 'tags': ['domain']}),
    mk("aws-cloudfront", "Amazon CloudFront", "net-cdn-dns", "cdn",
       "AWS 全球 CDN 与边缘计算", "https://aws.amazon.com/cloudfront/",
       "CloudFront 与 AWS 生态深度集成，支持 S3/Lambda@Edge，适合已在 AWS 上的静态与动态加速。", "静态资源在 S3、API 在 AWS 且需全球低延迟分发时默认 CDN 选择。", "定价维度多（请求/流量/功能）；非 AWS 栈配置 cross-cloud 较麻烦。",
       **{'vendorId': 'amazon', 'tags': ['cdn', 'aws']}),
    mk("bunny-cdn", "Bunny CDN", "net-cdn-dns", "cdn",
       "高性价比 CDN 与存储", "https://bunny.net",
       "Bunny.net 提供低价 CDN、optimizer 与 edge storage，Perf 与价格比传统 CDN 对 indie 友好。", "预算敏感但需要多 PoP 加速、或替代 CloudFront 降本时评估 Bunny。", "Enterprise 功能与支持不如 Akamai/Cloudflare；国内节点覆盖需查最新 map。",
       **{'vendorId': 'bunny-net', 'tags': ['cdn']}),
    mk("aliyun-cdn", "阿里云 CDN", "net-cdn-dns", "cdn",
       "国内节点丰富的 CDN 加速", "https://www.aliyun.com/product/cdn",
       "阿里云 CDN 覆盖国内 ISP 与海外节点，与 OSS/ECS 集成，备案域名加速标配。", "面向国内用户的主站静态资源、下载与直播加速且已有阿里云账号时选用。", "必须 ICP 备案域名；HTTPS 证书与回源配置错误易导致循环或 5xx。",
       **{'vendorId': 'aliyun', 'tags': ['cdn'], 'region': 'domestic'}),
    mk("fastly", "Fastly", "net-cdn-dns", "cdn",
       "实时配置的边缘 CDN", "https://www.fastly.com",
       "Fastly 以 instant purge、Compute@Edge 与细粒度 VCL 控制著称，媒体与 API 加速场景多。", "需要秒级 cache purge、或 edge 逻辑（auth/geo）时评估 Fastly。", "价格比 Bunny/Cloudflare 高；配置复杂度高于「开箱 CDN」。",
       **{'vendorId': 'fastly-inc', 'tags': ['cdn', 'edge']}),
    mk("route53", "Amazon Route 53", "net-cdn-dns", "dns",
       "AWS 权威 DNS 与 health check", "https://aws.amazon.com/route53/",
       "Route 53 提供 DNS hosting、traffic routing 与 health check，与 AWS 其他服务集成紧密。", "域名 DNS 托管在 AWS、或需要 weighted/failover routing 时采用。", "按 query 计费；非 AWS 用户仅为 DNS 用 Cloudflare 更常见。",
       **{'vendorId': 'amazon', 'tags': ['dns']}),
    mk("google-cloud-dns", "Google Cloud DNS", "net-cdn-dns", "dns",
       "GCP 权威 DNS 服务", "https://cloud.google.com/dns",
       "Cloud DNS 提供低延迟 anycast DNS 与 DNSSEC，适合 GCP 工作负载与 hybrid DNS 策略。", "基础设施在 GCP、或需要 programmatic DNS 与 Terraform 管理记录时选用。", "UI 与生态不如 Cloudflare 一体化；仅 DNS 无 CDN 需另配。",
       **{'vendorId': 'google', 'tags': ['dns']}),
    mk("gandi", "Gandi.net", "net-domain", "registrar",
       "道德域名商与简单 DNS", "https://www.gandi.net",
       "Gandi 强调 privacy、透明 pricing 与「no bullshit」品牌，提供域名、邮箱与 hosting 基础服务。", "欧洲项目重视 registrar ethics、或需要 .fr 等本地 TLD 时可考虑 Gandi。", "价格不一定最低；高级 DNS/CDN 仍需 Cloudflare。",
       **{'vendorId': 'gandi-inc', 'tags': ['domain']}),
    mk("keycdn", "KeyCDN", "net-cdn-dns", "cdn",
       "轻量低价 CDN", "https://www.keycdn.com",
       "KeyCDN 提供简单 pay-as-you-go CDN 与 image processing，适合中小流量站点降本。", "流量中等、希望比 CloudFront 简单计费且不需 WAF 时可选 KeyCDN。", "功能面小于 Cloudflare；国内加速非强项。",
       **{'vendorId': 'keycdn-inc', 'tags': ['cdn']}),
    mk("aws-secrets-manager", "AWS Secrets Manager", "sec-secrets", "secrets",
       "AWS 托管密钥轮换", "https://aws.amazon.com/secrets-manager/",
       "Secrets Manager 存储 API key/DB 凭证并支持自动轮换，与 Lambda/RDS IAM 集成，减少明文 env。", "全栈在 AWS、需 audit 与 rotation 的 secrets 管理时采用；替代 .env 进 repo。", "按 secret 数量计费；跨 region replicate 要额外配置。",
       **{'vendorId': 'amazon', 'tags': ['secrets', 'aws']}),
    mk("gcp-secret-manager", "Google Secret Manager", "sec-secrets", "secrets",
       "GCP 托管密钥存储", "https://cloud.google.com/secret-manager",
       "Secret Manager 在 GCP 集中管理 secret 版本、IAM 访问与 audit log，与 Cloud Run/GKE 集成。", "工作负载在 GCP、或已有 Google Cloud 组织 policy 时统一管理 secrets。", "无内置 rotation 需 Cloud Functions 配合；multi-cloud 需另配。",
       **{'vendorId': 'google', 'tags': ['secrets']}),
    mk("sops", "Mozilla SOPS", "sec-secrets", "secrets",
       "加密文件中的 secrets 管理", "https://github.com/getsops/sops",
       "SOPS 对 YAML/JSON/env 文件中的值加密，可 git 存储密文 secrets，适合 GitOps 仓库。", "希望 secrets 与 infra code 同 repo 但 ciphertext 可 PR review 时采用 SOPS+age/KMS。", "密钥管理与 rotation 流程需自建；误 commit plaintext 仍可能发生。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['secrets', 'gitops']}),
    mk("snyk", "Snyk", "sec-secrets", "scanning",
       "依赖与容器漏洞扫描", "https://snyk.io",
       "Snyk 扫描开源依赖、容器镜像与 IaC 漏洞，集成 GitHub/GitLab PR checks，DevSecOps 常见。", "需要在 CI 阻断 critical CVE、或持续监控 npm/Docker 供应链时启用 Snyk。", "误报与 noise 需 tuning；高级 license 扫描另付费。",
       **{'vendorId': 'snyk-inc', 'tags': ['security', 'dependencies']}),
    mk("cloudflare-waf", "Cloudflare WAF", "sec-secrets", "waf",
       "边缘 Web 应用防火墙", "https://www.cloudflare.com/application-services/products/waf/",
       "Cloudflare WAF 在 CDN 边缘拦截 OWASP Top 10、bot 与 custom rules，与 DDoS 防护一体。", "站点已走 Cloudflare CDN、需要基础 WAF 与 rate limit 而不另购硬件时启用规则集。", "高级 bot management 需 Enterprise；规则误杀要监控 false positive。",
       **{'vendorId': 'cloudflare-inc', 'tags': ['waf', 'cdn']}),
    mk("bitwarden", "Bitwarden", "sec-secrets", "password-manager",
       "开源密码管理器", "https://bitwarden.com",
       "Bitwarden 提供个人/团队密码 vault、secrets manager 与 SSO，可自托管，价格低于 1Password。", "团队共享 infra/login 凭证、或开发者需要安全密码库时采用；可替代 spreadsheet 存密。", "自托管需维护；紧急 access 与 offboarding 流程要制度化。",
       **{'vendorId': 'bitwarden-inc', 'tags': ['passwords']}),
    mk("trivy", "Trivy", "sec-secrets", "scanning",
       "全面开源安全扫描器", "https://trivy.dev",
       "Trivy 扫描容器镜像、filesystem、IaC 与 SBOM，CI 集成简单，Aqua 维护。", "GitHub Actions 中免费替代部分 Snyk 能力、或 air-gapped 环境需离线扫描时使用。", "结果聚合与 policy-as-code 需搭配 OPA/DefectDojo；非 SaaS dashboard。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['scanning', 'containers']}),
    mk("sonarqube", "SonarQube", "sec-secrets", "scanning",
       "代码质量与安全门禁", "https://www.sonarsource.com/products/sonarqube/",
       "SonarQube 静态分析 code smell、bug 与安全 hotspot，企业版支持 quality gate 阻断 merge。", "受监管行业需要 central code quality dashboard 与 long-term trend 时部署 SonarQube。", "自托管资源消耗大；规则 tuning 不当会拖慢 PR。",
       **{'vendorId': 'sonarsource', 'tags': ['sast', 'quality']}),
    mk("checkov", "Checkov", "sec-secrets", "scanning",
       "IaC 策略即代码扫描", "https://www.checkov.io",
       "Checkov 扫描 Terraform/CloudFormation/K8s manifest 的 misconfiguration，Bridgecrew/Prisma 生态，CI 友好。", "Terraform pipeline 需要在 plan 阶段 catch 公开 S3 等错误配置时加入 Checkov。", "仅静态规则；runtime 攻击面需另层 WAF/runtime security。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['iac', 'security']}),
    mk("aws-waf", "AWS WAF", "sec-secrets", "waf",
       "AWS 托管 WAF 规则", "https://aws.amazon.com/waf/",
       "AWS WAF 附加 ALB/CloudFront/API Gateway，托管 rule group 与 custom rules，与 AWS Shield 配合。", "基础设施在 AWS 且需在 L7 做 geo block、rate limit 时不另引 Cloudflare 时可选用。", "规则成本按 capacity unit 计；与 Cloudflare 比配置分散在 AWS 控制台。",
       **{'vendorId': 'amazon', 'tags': ['waf', 'aws']}),
    mk("framer", "Framer", "design-tools", "prototype",
       "设计与发布一体化 Web", "https://www.framer.com",
       "Framer 从原型工具演进为可直接发布站点的设计平台，动画与 responsive 强，marketing 页快速上线。", "营销页/landing 需要设计师主导、少写代码即可 publish 时选用 Framer。", "复杂 app logic 仍要 dev 接手；SEO 与 CMS 能力视 plan 而定。",
       **{'vendorId': 'framer-inc', 'tags': ['design', 'website']}),
    mk("penpot", "Penpot", "design-tools", "ui-design",
       "开源 Figma 替代", "https://penpot.app",
       "Penpot 是开源 design/collab 工具，支持 SVG/CSS 导出，可自托管，适合对设计文件主权有要求的团队。", "不能采购 Figma、或需 EU 开源设计栈时评估 Penpot；与 dev handoff 通过 open format。", "插件与生态远小于 Figma；大型 design system 迁移成本高。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['design', 'ui']}),
    mk("stable-diffusion", "Stable Diffusion", "design-ai-image", "image-gen",
       "开源扩散模型图像生成", "https://stability.ai/stable-diffusion",
       "Stable Diffusion 开源文生图/图生图模型，可本地或云端运行，LoRA/DreamBooth 生态丰富。", "需要可控成本的批量素材、或私有化生成不宜上传商业机密 prompt 时自托管 SD。", "模型版权与生成内容合规需法务评估；硬件 GPU 成本不低。",
       **{'vendorId': 'stability-ai', 'tags': ['ai', 'image']}),
    mk("ideogram", "Ideogram", "design-ai-image", "image-gen",
       "擅长文字排版的 AI 图像", "https://ideogram.ai",
       "Ideogram 在 AI 生成图中渲染可读文字与 logo 表现突出，适合 poster 与 social creative。", "需要营销图内嵌 slogan/标题且少后期 PS 文字时试用 Ideogram。", "风格控制与 consistency 不如 Midjourney 艺术向；API 与 batch 能力查最新。",
       **{'vendorId': 'ideogram-inc', 'tags': ['ai', 'image']}),
    mk("recraft", "Recraft", "design-ai-image", "image-gen",
       "矢量风格 AI 设计", "https://www.recraft.ai",
       "Recraft 专注 brand-consistent 矢量插画与 icon 生成，支持 style reference，适合 UI 资产批量产出。", "设计系统需要统一插画风格、导出 SVG 用于 web/app 时评估 Recraft。", "照片级 realism 非强项；商业 license 条款需读清。",
       **{'vendorId': 'recraft-inc', 'tags': ['ai', 'vector']}),
    mk("flux-ai", "Flux", "design-ai-image", "image-gen",
       "高质量开源图像模型族", "https://blackforestlabs.ai",
       "Flux 由 Black Forest Labs 发布，提供 pro/dev/schnell 档位，质量与速度平衡好，API 与 ComfyUI 生态增长快。", "需要 Midjourney 级质量又希望 API 集成到产品 pipeline 时评估 Flux API/自托管 dev 权重。", "pro 模型 licensing 与 NSFW 政策需遵守；算力成本随分辨率上升。",
       **{'vendorId': 'black-forest-labs', 'tags': ['ai', 'image']}),
    mk("unsplash", "Unsplash", "design-tools", "stock",
       "高质量免费摄影图库", "https://unsplash.com",
       "Unsplash 提供免费高分辨率照片与 API，广泛用于 marketing 与 mockup，license 相对宽松（仍须遵守 terms）。", "需要快速找 hero 图、或产品内 placeholder 图库集成时使用 Unsplash API。", "热门图过度使用显「模板感」；商业项目仍建议自有摄影或 paid stock。",
       **{'vendorId': 'unsplash-inc', 'tags': ['stock', 'photos'], 'pricing': {'model': 'free'}}),
    mk("pexels", "Pexels", "design-tools", "stock",
       "免费图库与视频素材", "https://www.pexels.com",
       "Pexels 提供免费 stock photos/videos，与 Canva 等同生态，适合 indie 内容与博客配图。", "视频 b-roll 与静态图都要免费源时 Pexels 一站式；API 集成简单。", "与 Unsplash 内容重叠多；注意 model release 与 attribution 要求变化。",
       **{'vendorId': 'canva', 'tags': ['stock'], 'pricing': {'model': 'free'}}),
    mk("rive", "Rive", "design-motion", "animation",
       "交互式矢量动画运行时", "https://rive.app",
       "Rive 提供编辑器与轻量 runtime，在 app/web 中播放交互 animation，文件小于 Lottie 某些场景。", "需要复杂 state machine 动画、游戏化 UI 或 character rig 时评估 Rive vs Lottie。", "设计师学习曲线；旧项目大量 Lottie 迁移需成本。",
       **{'vendorId': 'rive-inc', 'tags': ['animation', 'interactive']}),
    mk("undraw", "unDraw", "design-tools", "illustration",
       "开源 SVG 插画库", "https://undraw.co",
       "unDraw 提供可换主色的一致风格 open-source 插画，SVG 可内联或下载，适合 SaaS landing、empty state 与 onboarding 场景。", "早期产品需要统一插画风格又不想雇插画师时快速填充 UI；与 Tailwind 色板配合换色方便。", "风格辨识度单一、易显「模板站」感；规模化品牌需定制插画体系或混合 paid stock。",
       **{'tags': ['illustration'], 'pricing': {'model': 'free'}}),
    mk("adobe-firefly", "Adobe Firefly", "design-ai-image", "image-gen",
       "Adobe 商用安全 AI 图像", "https://www.adobe.com/products/firefly.html",
       "Firefly 集成 Creative Cloud，强调 Content Credentials 与 commercial safe training data，企业合规友好。", "设计团队已 Adobe CC、需要 AI 生成与 Photoshop 无缝往返时启用 Firefly。", "闭源生态锁定；独立 API 能力与 SD/Flux 比需 benchmark。",
       **{'vendorId': 'adobe', 'tags': ['ai', 'image']}),
    mk("leonardo-ai", "Leonardo.Ai", "design-ai-image", "image-gen",
       "游戏与资产向 AI 图像平台", "https://leonardo.ai",
       "Leonardo 提供 fine-tuned models、sprite sheet 与 asset pipeline，游戏与 NFT 时代起家，现扩 general creative。", "需要 consistent character、game asset 或 controlnet 工作流时试用 Leonardo。", "免费额度有限；生成内容 license 用于 commercial 需确认 plan。",
       **{'vendorId': 'leonardo-inc', 'tags': ['ai', 'game-art']}),
    mk("spline", "Spline", "design-tools", "3d",
       "浏览器 3D 设计与 embed", "https://spline.design",
       "Spline 让设计师在 web 中创建 3D 场景并 embed 到 React/Framer，降低 product 3D hero 成本。", "marketing 需要 interactive 3D 而非静态图、且无专职 Three.js 工程师时选用 Spline。", "复杂游戏级 3D 仍要专业 DCC；runtime 性能 mobile 需测试。",
       **{'vendorId': 'spline-inc', 'tags': ['3d', 'web']}),
    mk("runway", "Runway", "design-ai-image", "video-gen",
       "AI 视频生成与编辑", "https://runwayml.com",
       "Runway 提供 Gen-3 等视频生成、inpainting 与 motion brush，影视级 previs 与 social video 常用。", "短视频营销、product demo 需要 AI video 而非静态 banner 时评估 Runway。", "按 credit 计费昂贵；生成视频版权与 deepfake 合规要严格。",
       **{'vendorId': 'runway-inc', 'tags': ['ai', 'video']}),
    mk("canva", "Canva", "design-tools", "template",
       "模板化设计与品牌套件", "https://www.canva.com",
       "Canva 提供 drag-drop 设计、品牌 kit 与团队协作，非设计师也能产出 social/deck 素材。", "市场/运营团队自助产出素材、减少找设计师排期时启用 Canva Business。", "精细 design system 与 dev handoff 不如 Figma；API 自动化有限。",
       **{'vendorId': 'canva', 'tags': ['design', 'templates']}),
    mk("jira", "Jira", "collab-pm", "issue-tracker",
       "敏捷 issue 与项目跟踪", "https://www.atlassian.com/software/jira",
       "Jira Software 提供 scrum/kanban board、workflow 定制与 Confluence 集成，enterprise 研发管理标配。", "中大型工程团队需要复杂 workflow、与 Bitbucket/GitHub 联动 traceability 时采用 Jira。", "配置过重、非工程同事抵触；小团队 Linear 更轻。",
       **{'vendorId': 'atlassian', 'tags': ['pm', 'agile']}),
    mk("trello", "Trello", "collab-pm", "kanban",
       "简单看板式任务管理", "https://trello.com",
       "Trello 以 board/list/card 组织任务，上手极快，适合小团队与个人项目轻量 tracking。", "非软件团队或早期 startup 需要零培训 kanban 时选用 Trello。", "规模化后缺乏 sprint/report；Power-Up 过多会碎片化。",
       **{'vendorId': 'atlassian', 'tags': ['kanban', 'simple']}),
    mk("asana", "Asana", "collab-pm", "work-management",
       "跨团队 work management", "https://asana.com",
       "Asana 连接 goals、projects、timeline 与 automation，适合 marketing+product+ops 混合协作。", "多部门共享 roadmap、需要 timeline/Gantt 视图而非纯 dev issue 时评估 Asana。", "engineering 深度集成不如 Jira/Linear；价格随 seats 上升。",
       **{'vendorId': 'asana-inc', 'tags': ['pm']}),
    mk("confluence", "Confluence", "collab-docs", "wiki",
       "企业 wiki 与知识库", "https://www.atlassian.com/software/confluence",
       "Confluence 与 Jira 同源，提供空间、模板与权限，存 PRD/runbook/会议纪要。", "已买 Atlassian 套件、工程文档要与 Jira issue 互链时默认 wiki。", "搜索与 editor 体验弱于 Notion；macro 页面维护成本高。",
       **{'vendorId': 'atlassian', 'tags': ['wiki', 'docs']}),
    mk("outline", "Outline", "collab-docs", "wiki",
       "现代开源团队 wiki", "https://www.getoutline.com",
       "Outline 提供 Notion 式编辑、slack 集成与 SSO，可自托管，适合 tech team knowledge base。", "希望 wiki 自主可控、又要有 nice UX 且可 docker 部署时选 Outline。", "移动端与 offline 弱；大型 attachment 存储要配 S3。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['wiki']}),
    mk("yuque", "语雀", "collab-docs", "wiki",
       "国内团队知识库与文档", "https://www.yuque.com",
       "语雀提供结构化文档、表格、画板与团队空间，中文 UX 与移动端阅读体验好，阿里系与大量国内互联网团队常用。", "国内团队知识沉淀、需要中文协作、权限分级与移动端阅读时首选之一；可与钉钉集成。", "国际化与开放 API 生态弱于 Notion；大规模导出 migration 需提前规划 Markdown/附件迁移脚本。",
       **{'vendorId': 'alibaba', 'tags': ['docs'], 'region': 'domestic'}),
    mk("height", "Height", "collab-pm", "issue-tracker",
       "AI 辅助的现代 issue tracker", "https://height.app",
       "Height 强调 speed、keyboard-first 与 AI 摘要，定位 Linear 竞争者，视图灵活。", "想要 Linear 类体验、又需要更强 spreadsheet 视图时评估 Height。", "生态与集成少于 Jira/Linear；团队规模超大时待验证。",
       **{'vendorId': 'height-inc', 'tags': ['pm']}),
    mk("plane-so", "Plane", "collab-pm", "issue-tracker",
       "开源 Linear/Jira 替代", "https://plane.so",
       "Plane 提供 issues、cycles、modules 与 pages，开源可自托管，适合希望 PM 工具自主可控的团队。", "不想为 Linear 付 SaaS、又需要 modern UX 的可自托管 PM 时部署 Plane。", "Enterprise SSO/audit 仍在完善；自行运维 Postgres/S3。",
       **{'pricing': {'model': 'open-source'}, 'tags': ['pm', 'self-hosted']}),
    mk("clickup", "ClickUp", "collab-pm", "work-management",
       "All-in-one 任务/Docs/Goals", "https://clickup.com",
       "ClickUp 合并 tasks、docs、whiteboard 与 time tracking，功能堆叠极多，适合希望一个 app 管全部的小中型团队。", "团队想减少 Notion+Jira+Trello 工具碎片且可接受学习曲线时试用 ClickUp。", "功能过载导致性能与 focus 问题；dev workflow 不如专用 issue tracker。",
       **{'vendorId': 'clickup-inc', 'tags': ['pm', 'docs']}),
    mk("monday", "monday.com", "collab-pm", "work-management",
       "可视化 work OS", "https://monday.com",
       "monday.com 以 colorful board 与 automation 连接跨部门流程，偏 ops/marketing 可视化项目管理。", "非纯工程团队需要 CRM-like project 视图与 no-code automation 时常见。", "软件开发 traceability 与 git 集成弱于 Jira/Linear；按 seat 计费。",
       **{'vendorId': 'monday-inc', 'tags': ['pm', 'ops']}),
    mk("basecamp", "Basecamp", "collab-pm", "work-management",
       "极简项目管理哲学", "https://basecamp.com",
       "Basecamp 主张 less is more：message board、to-dos、schedule 一体，拒绝 feature bloat，固定价 flat fee。", "远程小团队（<50）希望减少 PM 工具复杂度、重 async 沟通时适合 Basecamp。", "不适合复杂 agile metrics；与 GitHub 深度集成有限。",
       **{'vendorId': 'basecamp-inc', 'tags': ['pm', 'simple']}),
    mk("wrike", "Wrike", "collab-pm", "work-management",
       "企业级 work management", "https://www.wrike.com",
       "Wrike 提供 cross-functional Gantt、proofing 与 resource management，marketing+PMO 场景多。", "Enterprise 需要 portfolio 管理与复杂 approval workflow 时评估 Wrike。", "engineering 一线开发者体验不如 Linear；实施周期可能较长。",
       **{'vendorId': 'wrike-inc', 'tags': ['pm', 'enterprise']}),
    mk("shortcut", "Shortcut", "collab-pm", "issue-tracker",
       "formerly Clubhouse 的敏捷 tracker", "https://shortcut.com",
       "Shortcut 连接 roadmap、iteration 与 story，UI 比 Jira 轻，startup 工程团队口碑好。", "需要 Jira 能力 subset、重视 speed 与 roadmap 一屏展示时选用 Shortcut。", "Atlassian 生态集成弱；超大型 program 管理可能不足。",
       **{'vendorId': 'shortcut-inc', 'tags': ['pm', 'agile']}),
    mk("coda", "Coda", "collab-docs", "docs",
       "文档+表格+app 混合", "https://coda.io",
       "Coda 把 docs、tables 与 button/automation 合成 lightweight app，适合 ops playbook 与 living spec。", "PRD/Runbook 需要结构化 table+ narrative 一体、又要轻 automation 时 Coda 介于 Notion/Airtable。", "大规模 wiki 性能与 permission 模型复杂；dev 仍可能另开 Linear。",
       **{'vendorId': 'coda-inc', 'tags': ['docs', 'automation']}),
    mk("slite", "Slite", "collab-docs", "wiki",
       "轻量团队知识库", "https://slite.com",
       "Slite 专注 clean docs、AI ask 与 channel 组织，比 Notion 更强调 team handbook 与 onboarding doc。", "远程团队需要 maintainable handbook、减少 Notion 杂乱 workspace 时试用 Slite。", "database/views 能力弱于 Notion；国内访问需评估。",
       **{'vendorId': 'slite-inc', 'tags': ['docs', 'wiki']}),
    mk("microsoft-loop", "Microsoft Loop", "collab-suite", "suite",
       "Microsoft 365 协作组件", "https://www.microsoft.com/microsoft-loop",
       "Loop 提供 portable component 嵌入 Teams/Outlook/Word，实时 co-edit 与 task 跟踪，M365 生态扩展。", "公司已 M365、希望在 Teams 内嵌 living doc component 而非另开 Notion 时启用 Loop。", "Standalone 体验仍不如 Notion；guest 与 licensing 复杂。",
       **{'vendorId': 'microsoft', 'tags': ['suite', 'docs']}),
]

VENDORS: list[dict] = [{'id': 'vercel-inc', 'name': 'Vercel', 'region': 'overseas', 'url': 'https://vercel.com'}, {'id': 'datadog-inc', 'name': 'Datadog', 'region': 'overseas', 'url': 'https://www.datadoghq.com'}, {'id': 'betterstack-inc', 'name': 'Better Stack', 'region': 'overseas', 'url': 'https://betterstack.com'}, {'id': 'newrelic-inc', 'name': 'New Relic', 'region': 'overseas', 'url': 'https://newrelic.com'}, {'id': 'honeycomb-io', 'name': 'Honeycomb', 'region': 'overseas', 'url': 'https://www.honeycomb.io'}, {'id': 'bugsnag-inc', 'name': 'Bugsnag', 'region': 'overseas', 'url': 'https://www.bugsnag.com'}, {'id': 'rollbar-inc', 'name': 'Rollbar', 'region': 'overseas', 'url': 'https://rollbar.com'}, {'id': 'logrocket-inc', 'name': 'LogRocket', 'region': 'overseas', 'url': 'https://logrocket.com'}, {'id': 'elastic-inc', 'name': 'Elastic', 'region': 'overseas', 'url': 'https://www.elastic.co'}, {'id': 'dynatrace-inc', 'name': 'Dynatrace', 'region': 'overseas', 'url': 'https://www.dynatrace.com'}, {'id': 'gitlab-inc', 'name': 'GitLab', 'region': 'overseas', 'url': 'https://about.gitlab.com'}, {'id': 'hashicorp', 'name': 'HashiCorp', 'region': 'overseas', 'url': 'https://www.hashicorp.com'}, {'id': 'circleci-inc', 'name': 'CircleCI', 'region': 'overseas', 'url': 'https://circleci.com'}, {'id': 'buildkite-inc', 'name': 'Buildkite', 'region': 'overseas', 'url': 'https://buildkite.com'}, {'id': 'red-hat', 'name': 'Red Hat', 'region': 'overseas', 'url': 'https://www.redhat.com'}, {'id': 'railway-app', 'name': 'Railway', 'region': 'overseas', 'url': 'https://railway.app'}, {'id': 'twilio-inc', 'name': 'Twilio', 'region': 'overseas', 'url': 'https://www.twilio.com'}, {'id': 'activecampaign', 'name': 'ActiveCampaign', 'region': 'overseas', 'url': 'https://www.activecampaign.com'}, {'id': 'amazon', 'name': 'Amazon Web Services', 'region': 'overseas', 'url': 'https://aws.amazon.com'}, {'id': 'aliyun', 'name': '阿里云', 'region': 'domestic', 'url': 'https://www.aliyun.com'}, {'id': 'tencent-cloud', 'name': '腾讯云', 'region': 'domestic', 'url': 'https://cloud.tencent.com'}, {'id': 'jiguang', 'name': '极光', 'region': 'domestic', 'url': 'https://www.jiguang.cn'}, {'id': 'getui-inc', 'name': '个推', 'region': 'domestic', 'url': 'https://www.getui.com'}, {'id': 'onesignal-inc', 'name': 'OneSignal', 'region': 'overseas', 'url': 'https://onesignal.com'}, {'id': 'salesforce', 'name': 'Salesforce', 'region': 'overseas', 'url': 'https://www.salesforce.com'}, {'id': 'discord-inc', 'name': 'Discord', 'region': 'overseas', 'url': 'https://discord.com'}, {'id': 'alibaba', 'name': '阿里巴巴', 'region': 'domestic', 'url': 'https://www.alibaba.com'}, {'id': 'microsoft', 'name': 'Microsoft', 'region': 'overseas', 'url': 'https://www.microsoft.com'}, {'id': 'sinch', 'name': 'Sinch', 'region': 'overseas', 'url': 'https://www.sinch.com'}, {'id': 'brevo-inc', 'name': 'Brevo', 'region': 'overseas', 'url': 'https://www.brevo.com'}, {'id': 'apple', 'name': 'Apple', 'region': 'overseas', 'url': 'https://www.apple.com'}, {'id': 'mixpanel-inc', 'name': 'Mixpanel', 'region': 'overseas', 'url': 'https://mixpanel.com'}, {'id': 'amplitude-inc', 'name': 'Amplitude', 'region': 'overseas', 'url': 'https://amplitude.com'}, {'id': 'sensorsdata', 'name': '神策数据', 'region': 'domestic', 'url': 'https://www.sensorsdata.cn'}, {'id': 'growingio', 'name': 'GrowingIO', 'region': 'domestic', 'url': 'https://www.growingio.com'}, {'id': 'ahrefs-inc', 'name': 'Ahrefs', 'region': 'overseas', 'url': 'https://ahrefs.com'}, {'id': 'google', 'name': 'Google', 'region': 'overseas', 'url': 'https://google.com'}, {'id': 'hotjar-inc', 'name': 'Hotjar', 'region': 'overseas', 'url': 'https://www.hotjar.com'}, {'id': 'semrush-inc', 'name': 'Semrush', 'region': 'overseas', 'url': 'https://www.semrush.com'}, {'id': 'heap-inc', 'name': 'Heap', 'region': 'overseas', 'url': 'https://www.heap.io'}, {'id': 'fathom-inc', 'name': 'Fathom', 'region': 'overseas', 'url': 'https://usefathom.com'}, {'id': 'namecheap-inc', 'name': 'Namecheap', 'region': 'overseas', 'url': 'https://www.namecheap.com'}, {'id': 'porkbun-inc', 'name': 'Porkbun', 'region': 'overseas', 'url': 'https://porkbun.com'}, {'id': 'cloudflare-inc', 'name': 'Cloudflare', 'region': 'overseas', 'url': 'https://www.cloudflare.com'}, {'id': 'bunny-net', 'name': 'Bunny.net', 'region': 'overseas', 'url': 'https://bunny.net'}, {'id': 'fastly-inc', 'name': 'Fastly', 'region': 'overseas', 'url': 'https://www.fastly.com'}, {'id': 'gandi-inc', 'name': 'Gandi', 'region': 'overseas', 'url': 'https://www.gandi.net'}, {'id': 'keycdn-inc', 'name': 'KeyCDN', 'region': 'overseas', 'url': 'https://www.keycdn.com'}, {'id': 'snyk-inc', 'name': 'Snyk', 'region': 'overseas', 'url': 'https://snyk.io'}, {'id': 'bitwarden-inc', 'name': 'Bitwarden', 'region': 'overseas', 'url': 'https://bitwarden.com'}, {'id': 'sonarsource', 'name': 'SonarSource', 'region': 'overseas', 'url': 'https://www.sonarsource.com'}, {'id': 'framer-inc', 'name': 'Framer', 'region': 'overseas', 'url': 'https://www.framer.com'}, {'id': 'stability-ai', 'name': 'Stability AI', 'region': 'overseas', 'url': 'https://stability.ai'}, {'id': 'ideogram-inc', 'name': 'Ideogram', 'region': 'overseas', 'url': 'https://ideogram.ai'}, {'id': 'recraft-inc', 'name': 'Recraft', 'region': 'overseas', 'url': 'https://www.recraft.ai'}, {'id': 'black-forest-labs', 'name': 'Black Forest Labs', 'region': 'overseas', 'url': 'https://blackforestlabs.ai'}, {'id': 'unsplash-inc', 'name': 'Unsplash', 'region': 'overseas', 'url': 'https://unsplash.com'}, {'id': 'canva', 'name': 'Canva', 'region': 'overseas', 'url': 'https://www.canva.com'}, {'id': 'rive-inc', 'name': 'Rive', 'region': 'overseas', 'url': 'https://rive.app'}, {'id': 'adobe', 'name': 'Adobe', 'region': 'overseas', 'url': 'https://www.adobe.com'}, {'id': 'leonardo-inc', 'name': 'Leonardo.Ai', 'region': 'overseas', 'url': 'https://leonardo.ai'}, {'id': 'tailwind-labs', 'name': 'Tailwind Labs', 'region': 'overseas', 'url': 'https://tailwindcss.com'}, {'id': 'spline-inc', 'name': 'Spline', 'region': 'overseas', 'url': 'https://spline.design'}, {'id': 'runway-inc', 'name': 'Runway', 'region': 'overseas', 'url': 'https://runwayml.com'}, {'id': 'atlassian', 'name': 'Atlassian', 'region': 'overseas', 'url': 'https://www.atlassian.com'}, {'id': 'asana-inc', 'name': 'Asana', 'region': 'overseas', 'url': 'https://asana.com'}, {'id': 'height-inc', 'name': 'Height', 'region': 'overseas', 'url': 'https://height.app'}, {'id': 'clickup-inc', 'name': 'ClickUp', 'region': 'overseas', 'url': 'https://clickup.com'}, {'id': 'monday-inc', 'name': 'monday.com', 'region': 'overseas', 'url': 'https://monday.com'}, {'id': 'basecamp-inc', 'name': 'Basecamp', 'region': 'overseas', 'url': 'https://basecamp.com'}, {'id': 'wrike-inc', 'name': 'Wrike', 'region': 'overseas', 'url': 'https://www.wrike.com'}, {'id': 'shortcut-inc', 'name': 'Shortcut', 'region': 'overseas', 'url': 'https://shortcut.com'}, {'id': 'coda-inc', 'name': 'Coda', 'region': 'overseas', 'url': 'https://coda.io'}, {'id': 'slite-inc', 'name': 'Slite', 'region': 'overseas', 'url': 'https://slite.com'}]

EDGES: list[dict] = [
    edge("edge-eslint-biome-alternative-to", "eslint", "biome", "alternative_to", note="Biome 可替代 ESLint+Prettier"),
    edge("edge-eslint-prettier-commonly-used-with", "eslint", "prettier", "commonly_used_with"),
    edge("edge-prettier-eslint-commonly-used-with", "prettier", "eslint", "commonly_used_with"),
    edge("edge-esbuild-vite-built-on", "esbuild", "vite", "built_on", note="Vite 生产构建使用 Rollup，dev 用 esbuild"),
    edge("edge-esbuild-rollup-commonly-used-with", "esbuild", "rollup", "commonly_used_with"),
    edge("edge-turbopack-nextjs-part-of", "turbopack", "nextjs", "part_of"),
    edge("edge-webpack-babel-commonly-used-with", "webpack", "babel", "commonly_used_with"),
    edge("edge-vitest-vite-built-on", "vitest", "vite", "built_on"),
    edge("edge-vitest-playwright-commonly-used-with", "vitest", "playwright", "commonly_used_with", note="单元+E2E 分层"),
    edge("edge-playwright-github-actions-integrates-with", "playwright", "github-actions", "integrates_with"),
    edge("edge-prisma-postgresql-commonly-used-with", "prisma", "postgresql", "commonly_used_with"),
    edge("edge-prisma-nextjs-commonly-used-with", "prisma", "nextjs", "commonly_used_with"),
    edge("edge-turbo-pnpm-commonly-used-with", "turbo", "pnpm", "commonly_used_with"),
    edge("edge-turbo-github-actions-integrates-with", "turbo", "github-actions", "integrates_with"),
    edge("edge-nx-github-actions-integrates-with", "nx", "github-actions", "integrates_with"),
    edge("edge-storybook-react-commonly-used-with", "storybook", "react", "commonly_used_with"),
    edge("edge-storybook-vite-integrates-with", "storybook", "vite", "integrates_with"),
    edge("edge-swc-nextjs-built-on", "swc", "nextjs", "built_on"),
    edge("edge-oxlint-eslint-alternative-to", "oxlint", "eslint", "alternative_to"),
    edge("edge-oxlint-biome-alternative-to", "oxlint", "biome", "alternative_to"),
    edge("edge-husky-lint-staged-commonly-used-with", "husky", "lint-staged", "commonly_used_with"),
    edge("edge-changesets-pnpm-commonly-used-with", "changesets", "pnpm", "commonly_used_with"),
    edge("edge-changesets-github-actions-integrates-with", "changesets", "github-actions", "integrates_with"),
    edge("edge-rollup-vite-built-on", "rollup", "vite", "built_on"),
    edge("edge-babel-jest-commonly-used-with", "babel", "jest", "commonly_used_with"),
    edge("edge-jest-testing-library-commonly-used-with", "jest", "testing-library", "commonly_used_with"),
    edge("edge-vitest-testing-library-commonly-used-with", "vitest", "testing-library", "commonly_used_with"),
    edge("edge-cypress-github-actions-integrates-with", "cypress", "github-actions", "integrates_with"),
    edge("edge-semantic-release-github-actions-integrates-with", "semantic-release", "github-actions", "integrates_with"),
    edge("edge-renovate-github-actions-integrates-with", "renovate", "github-actions", "integrates_with"),
    edge("edge-msw-storybook-commonly-used-with", "msw", "storybook", "commonly_used_with"),
    edge("edge-rspack-webpack-migration-path-to", "rspack", "webpack", "migration_path_to"),
    edge("edge-rolldown-vite-built-on", "rolldown", "vite", "built_on"),
    edge("edge-npm-pnpm-alternative-to", "npm", "pnpm", "alternative_to"),
    edge("edge-yarn-pnpm-alternative-to", "yarn", "pnpm", "alternative_to"),
    edge("edge-knip-pnpm-commonly-used-with", "knip", "pnpm", "commonly_used_with"),
    edge("edge-datadog-docker-integrates-with", "datadog", "docker", "integrates_with"),
    edge("edge-datadog-grafana-alternative-to", "datadog", "grafana", "alternative_to"),
    edge("edge-prometheus-grafana-commonly-used-with", "prometheus", "grafana", "commonly_used_with"),
    edge("edge-loki-grafana-commonly-used-with", "loki", "grafana", "commonly_used_with"),
    edge("edge-jaeger-opentelemetry-integrates-with", "jaeger", "opentelemetry", "integrates_with"),
    edge("edge-signoz-opentelemetry-built-on", "signoz", "opentelemetry", "built_on"),
    edge("edge-highlight-io-sentry-alternative-to", "highlight-io", "sentry", "alternative_to"),
    edge("edge-betterstack-grafana-alternative-to", "betterstack", "grafana", "alternative_to"),
    edge("edge-honeycomb-opentelemetry-integrates-with", "honeycomb", "opentelemetry", "integrates_with"),
    edge("edge-logrocket-ga4-commonly-used-with", "logrocket", "ga4", "commonly_used_with"),
    edge("edge-openreplay-sentry-commonly-used-with", "openreplay", "sentry", "commonly_used_with"),
    edge("edge-glitchtip-sentry-open-source-alternative-to", "glitchtip", "sentry", "open_source_alternative_to"),
    edge("edge-gitlab-ci-docker-commonly-used-with", "gitlab-ci", "docker", "commonly_used_with"),
    edge("edge-kubernetes-docker-depends-on", "kubernetes", "docker", "depends_on"),
    edge("edge-terraform-docker-commonly-used-with", "terraform", "docker", "commonly_used_with"),
    edge("edge-terraform-pulumi-alternative-to", "terraform", "pulumi", "alternative_to"),
    edge("edge-circleci-github-actions-alternative-to", "circleci", "github-actions", "alternative_to"),
    edge("edge-buildkite-docker-commonly-used-with", "buildkite", "docker", "commonly_used_with"),
    edge("edge-argo-cd-kubernetes-depends-on", "argo-cd", "kubernetes", "depends_on"),
    edge("edge-argo-cd-helm-commonly-used-with", "argo-cd", "helm", "commonly_used_with"),
    edge("edge-flux-cd-kubernetes-depends-on", "flux-cd", "kubernetes", "depends_on"),
    edge("edge-earthly-docker-built-on", "earthly", "docker", "built_on"),
    edge("edge-nixpacks-docker-built-on", "nixpacks", "docker", "built_on"),
    edge("edge-nixpacks-railway-commonly-used-with", "nixpacks", "railway", "commonly_used_with"),
    edge("edge-tekton-kubernetes-depends-on", "tekton", "kubernetes", "depends_on"),
    edge("edge-helm-kubernetes-part-of", "helm", "kubernetes", "part_of"),
    edge("edge-dagger-docker-built-on", "dagger", "docker", "built_on"),
    edge("edge-jenkins-github-actions-migration-path-to", "jenkins", "github-actions", "migration_path_to"),
    edge("edge-sendgrid-twilio-part-of", "sendgrid", "twilio", "part_of"),
    edge("edge-sendgrid-resend-alternative-to", "sendgrid", "resend", "alternative_to"),
    edge("edge-postmark-resend-alternative-to", "postmark", "resend", "alternative_to"),
    edge("edge-aws-ses-resend-alternative-to", "aws-ses", "resend", "alternative_to"),
    edge("edge-aliyun-directmail-resend-domestic-equivalent-of", "aliyun-directmail", "resend", "domestic_equivalent_of"),
    edge("edge-aliyun-sms-twilio-domestic-equivalent-of", "aliyun-sms", "twilio", "domestic_equivalent_of"),
    edge("edge-tencent-sms-twilio-domestic-equivalent-of", "tencent-sms", "twilio", "domestic_equivalent_of"),
    edge("edge-jpush-firebase-fcm-domestic-equivalent-of", "jpush", "firebase-fcm", "domestic_equivalent_of"),
    edge("edge-getui-jpush-alternative-to", "getui", "jpush", "alternative_to"),
    edge("edge-onesignal-firebase-fcm-alternative-to", "onesignal", "firebase-fcm", "alternative_to"),
    edge("edge-slack-linear-integrates-with", "slack", "linear", "integrates_with"),
    edge("edge-slack-sentry-integrates-with", "slack", "sentry", "integrates_with"),
    edge("edge-discord-telegram-bot-alternative-to", "discord", "telegram-bot", "alternative_to"),
    edge("edge-dingtalk-feishu-alternative-to", "dingtalk", "feishu", "alternative_to"),
    edge("edge-dingtalk-wecom-alternative-to", "dingtalk", "wecom", "alternative_to"),
    edge("edge-microsoft-teams-feishu-alternative-to", "microsoft-teams", "feishu", "alternative_to"),
    edge("edge-mattermost-slack-open-source-alternative-to", "mattermost", "slack", "open_source_alternative_to"),
    edge("edge-mixpanel-ga4-commonly-used-with", "mixpanel", "ga4", "commonly_used_with"),
    edge("edge-mixpanel-posthog-alternative-to", "mixpanel", "posthog", "alternative_to"),
    edge("edge-amplitude-mixpanel-alternative-to", "amplitude", "mixpanel", "alternative_to"),
    edge("edge-sensorsdata-mixpanel-domestic-equivalent-of", "sensorsdata", "mixpanel", "domestic_equivalent_of"),
    edge("edge-growingio-mixpanel-domestic-equivalent-of", "growingio", "mixpanel", "domestic_equivalent_of"),
    edge("edge-google-search-console-ga4-commonly-used-with", "google-search-console", "ga4", "commonly_used_with"),
    edge("edge-microsoft-clarity-hotjar-alternative-to", "microsoft-clarity", "hotjar", "alternative_to"),
    edge("edge-matomo-ga4-open-source-alternative-to", "matomo", "ga4", "open_source_alternative_to"),
    edge("edge-matomo-plausible-alternative-to", "matomo", "plausible", "alternative_to"),
    edge("edge-segment-ga4-provides-access-to", "segment", "ga4", "provides_access_to"),
    edge("edge-fathom-plausible-alternative-to", "fathom", "plausible", "alternative_to"),
    edge("edge-fathom-umami-alternative-to", "fathom", "umami", "alternative_to"),
    edge("edge-heap-mixpanel-alternative-to", "heap", "mixpanel", "alternative_to"),
    edge("edge-namecheap-cloudflare-registrar-alternative-to", "namecheap", "cloudflare-registrar", "alternative_to"),
    edge("edge-porkbun-namecheap-alternative-to", "porkbun", "namecheap", "alternative_to"),
    edge("edge-cloudflare-registrar-cloudflare-cdn-part-of", "cloudflare-registrar", "cloudflare-cdn", "part_of"),
    edge("edge-aws-cloudfront-cloudflare-cdn-alternative-to", "aws-cloudfront", "cloudflare-cdn", "alternative_to"),
    edge("edge-bunny-cdn-cloudflare-cdn-alternative-to", "bunny-cdn", "cloudflare-cdn", "alternative_to"),
    edge("edge-aliyun-cdn-cloudflare-cdn-domestic-equivalent-of", "aliyun-cdn", "cloudflare-cdn", "domestic_equivalent_of"),
    edge("edge-aliyun-cdn-edgeone-alternative-to", "aliyun-cdn", "edgeone", "alternative_to"),
    edge("edge-fastly-cloudflare-cdn-alternative-to", "fastly", "cloudflare-cdn", "alternative_to"),
    edge("edge-route53-dnspod-alternative-to", "route53", "dnspod", "alternative_to"),
    edge("edge-google-cloud-dns-dnspod-alternative-to", "google-cloud-dns", "dnspod", "alternative_to"),
    edge("edge-aws-secrets-manager-doppler-alternative-to", "aws-secrets-manager", "doppler", "alternative_to"),
    edge("edge-aws-secrets-manager-hashicorp-vault-alternative-to", "aws-secrets-manager", "hashicorp-vault", "alternative_to"),
    edge("edge-gcp-secret-manager-infisical-alternative-to", "gcp-secret-manager", "infisical", "alternative_to"),
    edge("edge-sops-hashicorp-vault-commonly-used-with", "sops", "hashicorp-vault", "commonly_used_with"),
    edge("edge-snyk-github-actions-integrates-with", "snyk", "github-actions", "integrates_with"),
    edge("edge-cloudflare-waf-cloudflare-cdn-part-of", "cloudflare-waf", "cloudflare-cdn", "part_of"),
    edge("edge-bitwarden-onepassword-alternative-to", "bitwarden", "onepassword", "alternative_to"),
    edge("edge-trivy-github-actions-integrates-with", "trivy", "github-actions", "integrates_with"),
    edge("edge-checkov-terraform-integrates-with", "checkov", "terraform", "integrates_with"),
    edge("edge-sonarqube-github-actions-integrates-with", "sonarqube", "github-actions", "integrates_with"),
    edge("edge-framer-figma-alternative-to", "framer", "figma", "alternative_to"),
    edge("edge-penpot-figma-open-source-alternative-to", "penpot", "figma", "open_source_alternative_to"),
    edge("edge-stable-diffusion-midjourney-open-source-alternative-to", "stable-diffusion", "midjourney", "open_source_alternative_to"),
    edge("edge-ideogram-midjourney-alternative-to", "ideogram", "midjourney", "alternative_to"),
    edge("edge-flux-ai-midjourney-alternative-to", "flux-ai", "midjourney", "alternative_to"),
    edge("edge-recraft-figma-commonly-used-with", "recraft", "figma", "commonly_used_with"),
    edge("edge-adobe-firefly-figma-commonly-used-with", "adobe-firefly", "figma", "commonly_used_with"),
    edge("edge-leonardo-ai-midjourney-alternative-to", "leonardo-ai", "midjourney", "alternative_to"),
    edge("edge-rive-lottiefiles-alternative-to", "rive", "lottiefiles", "alternative_to"),
    edge("edge-unsplash-figma-commonly-used-with", "unsplash", "figma", "commonly_used_with"),
    edge("edge-pexels-unsplash-alternative-to", "pexels", "unsplash", "alternative_to"),
    edge("edge-spline-framer-commonly-used-with", "spline", "framer", "commonly_used_with"),
    edge("edge-canva-figma-alternative-to", "canva", "figma", "alternative_to"),
    edge("edge-jira-confluence-part-of", "jira", "confluence", "part_of"),
    edge("edge-jira-linear-alternative-to", "jira", "linear", "alternative_to"),
    edge("edge-trello-linear-alternative-to", "trello", "linear", "alternative_to"),
    edge("edge-asana-linear-alternative-to", "asana", "linear", "alternative_to"),
    edge("edge-confluence-notion-alternative-to", "confluence", "notion", "alternative_to"),
    edge("edge-outline-notion-open-source-alternative-to", "outline", "notion", "open_source_alternative_to"),
    edge("edge-yuque-notion-domestic-equivalent-of", "yuque", "notion", "domestic_equivalent_of"),
    edge("edge-yuque-feishu-commonly-used-with", "yuque", "feishu", "commonly_used_with"),
    edge("edge-height-linear-alternative-to", "height", "linear", "alternative_to"),
    edge("edge-plane-so-linear-open-source-alternative-to", "plane-so", "linear", "open_source_alternative_to"),
    edge("edge-clickup-notion-alternative-to", "clickup", "notion", "alternative_to"),
    edge("edge-monday-asana-alternative-to", "monday", "asana", "alternative_to"),
    edge("edge-basecamp-linear-alternative-to", "basecamp", "linear", "alternative_to"),
    edge("edge-shortcut-linear-alternative-to", "shortcut", "linear", "alternative_to"),
    edge("edge-coda-notion-alternative-to", "coda", "notion", "alternative_to"),
    edge("edge-slite-notion-alternative-to", "slite", "notion", "alternative_to"),
    edge("edge-microsoft-loop-notion-alternative-to", "microsoft-loop", "notion", "alternative_to"),
    edge("edge-wrike-asana-alternative-to", "wrike", "asana", "alternative_to"),
    edge("edge-parcel-vite-alternative-to", "parcel", "vite", "alternative_to"),
    edge("edge-stylelint-prettier-commonly-used-with", "stylelint", "prettier", "commonly_used_with"),
    edge("edge-commitlint-husky-commonly-used-with", "commitlint", "husky", "commonly_used_with"),
    edge("edge-lint-staged-husky-commonly-used-with", "lint-staged", "husky", "commonly_used_with"),
    edge("edge-tsup-esbuild-built-on", "tsup", "esbuild", "built_on"),
    edge("edge-release-please-changesets-alternative-to", "release-please", "changesets", "alternative_to"),
    edge("edge-size-limit-vite-commonly-used-with", "size-limit", "vite", "commonly_used_with"),
    edge("edge-moonrepo-turbo-alternative-to", "moonrepo", "turbo", "alternative_to"),
    edge("edge-newrelic-datadog-alternative-to", "newrelic", "datadog", "alternative_to"),
    edge("edge-bugsnag-sentry-alternative-to", "bugsnag", "sentry", "alternative_to"),
    edge("edge-rollbar-sentry-alternative-to", "rollbar", "sentry", "alternative_to"),
    edge("edge-tempo-grafana-part-of", "tempo", "grafana", "part_of"),
    edge("edge-elastic-apm-opentelemetry-compatible-with", "elastic-apm", "opentelemetry", "compatible_with"),
    edge("edge-dynatrace-datadog-alternative-to", "dynatrace", "datadog", "alternative_to"),
    edge("edge-ansible-terraform-commonly-used-with", "ansible", "terraform", "commonly_used_with"),
    edge("edge-packer-docker-commonly-used-with", "packer", "docker", "commonly_used_with"),
    edge("edge-mailgun-sendgrid-alternative-to", "mailgun", "sendgrid", "alternative_to"),
    edge("edge-brevo-sendgrid-alternative-to", "brevo", "sendgrid", "alternative_to"),
    edge("edge-apns-onesignal-commonly-used-with", "apns", "onesignal", "commonly_used_with"),
    edge("edge-zulip-slack-open-source-alternative-to", "zulip", "slack", "open_source_alternative_to"),
    edge("edge-ahrefs-google-search-console-commonly-used-with", "ahrefs", "google-search-console", "commonly_used_with"),
    edge("edge-semrush-ahrefs-alternative-to", "semrush", "ahrefs", "alternative_to"),
    edge("edge-hotjar-microsoft-clarity-alternative-to", "hotjar", "microsoft-clarity", "alternative_to"),
    edge("edge-gandi-namecheap-alternative-to", "gandi", "namecheap", "alternative_to"),
    edge("edge-keycdn-bunny-cdn-alternative-to", "keycdn", "bunny-cdn", "alternative_to"),
    edge("edge-aws-waf-cloudflare-waf-alternative-to", "aws-waf", "cloudflare-waf", "alternative_to"),
    edge("edge-undraw-figma-commonly-used-with", "undraw", "figma", "commonly_used_with"),
    edge("edge-runway-midjourney-alternative-to", "runway", "midjourney", "alternative_to"),
    edge("edge-testing-library-vitest-commonly-used-with", "testing-library", "vitest", "commonly_used_with"),
    edge("edge-telegram-bot-discord-alternative-to", "telegram-bot", "discord", "alternative_to"),
]
